-- Complete the Regulation Set M-B Pokémon catalog.
-- This migration runs once during deployment; request handlers remain read-only.

UPDATE `master_data` SET `name` = 'ニャオニクス（オスのすがた）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'pokemon' AND `name` = 'ニャオニクス';
--> statement-breakpoint
UPDATE `master_data` SET `name` = 'ギルガルド（シールドフォルム）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'pokemon' AND `name` = 'ギルガルド';
--> statement-breakpoint
UPDATE `master_data` SET `name` = 'パンプジン（ふつうのサイズ）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'pokemon' AND `name` = 'パンプジン';
--> statement-breakpoint
UPDATE `master_data` SET `name` = 'ルガルガン（まひるのすがた）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'pokemon' AND `name` = 'ルガルガン';
--> statement-breakpoint
UPDATE `master_data` SET `name` = 'イダイトウ（オスのすがた）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'pokemon' AND `name` = 'イダイトウ';
--> statement-breakpoint
UPDATE `master_data` SET `name` = 'イルカマン（ナイーブフォルム）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'pokemon' AND `name` = 'イルカマン';
--> statement-breakpoint
UPDATE `master_data` SET `name` = 'メガニャオニクス（オスのすがた）', `updated_at` = CURRENT_TIMESTAMP WHERE `category` = 'form' AND `name` = 'メガニャオニクス';
--> statement-breakpoint

INSERT INTO `master_data` (`category`, `name`, `type`, `description`, `data`) VALUES
  ('pokemon', 'フシギバナ', 'くさ・どく', '全国図鑑No.0003。Pokémon Championsで使用できるポケモン。', '{"dexNo":3,"champions":true,"stats":{"hp":80,"attack":82,"defense":83,"spAttack":100,"spDefense":100,"speed":80}}'),
  ('pokemon', 'リザードン', 'ほのお・ひこう', '全国図鑑No.0006。Pokémon Championsで使用できるポケモン。', '{"dexNo":6,"champions":true,"stats":{"hp":78,"attack":84,"defense":78,"spAttack":109,"spDefense":85,"speed":100}}'),
  ('pokemon', 'カメックス', 'みず', '全国図鑑No.0009。Pokémon Championsで使用できるポケモン。', '{"dexNo":9,"champions":true,"stats":{"hp":79,"attack":83,"defense":100,"spAttack":85,"spDefense":105,"speed":78}}'),
  ('pokemon', 'スピアー', 'むし・どく', '全国図鑑No.0015。Pokémon Championsで使用できるポケモン。', '{"dexNo":15,"champions":true,"stats":{"hp":65,"attack":90,"defense":40,"spAttack":45,"spDefense":80,"speed":75}}'),
  ('pokemon', 'ピジョット', 'ノーマル・ひこう', '全国図鑑No.0018。Pokémon Championsで使用できるポケモン。', '{"dexNo":18,"champions":true,"stats":{"hp":83,"attack":80,"defense":75,"spAttack":70,"spDefense":70,"speed":101}}'),
  ('pokemon', 'アーボック', 'どく', '全国図鑑No.0024。Pokémon Championsで使用できるポケモン。', '{"dexNo":24,"champions":true,"stats":{"hp":60,"attack":95,"defense":69,"spAttack":65,"spDefense":79,"speed":80}}'),
  ('pokemon', 'ピカチュウ', 'でんき', '全国図鑑No.0025。Pokémon Championsで使用できるポケモン。', '{"dexNo":25,"champions":true,"stats":{"hp":35,"attack":55,"defense":40,"spAttack":50,"spDefense":50,"speed":90}}'),
  ('pokemon', 'ライチュウ', 'でんき', '全国図鑑No.0026。Pokémon Championsで使用できるポケモン。', '{"dexNo":26,"champions":true,"stats":{"hp":60,"attack":90,"defense":55,"spAttack":90,"spDefense":80,"speed":110}}'),
  ('pokemon', 'ピクシー', 'フェアリー', '全国図鑑No.0036。Pokémon Championsで使用できるポケモン。', '{"dexNo":36,"champions":true,"stats":{"hp":95,"attack":70,"defense":73,"spAttack":95,"spDefense":90,"speed":60}}'),
  ('pokemon', 'キュウコン', 'ほのお', '全国図鑑No.0038。Pokémon Championsで使用できるポケモン。', '{"dexNo":38,"champions":true,"stats":{"hp":73,"attack":76,"defense":75,"spAttack":81,"spDefense":100,"speed":100}}'),
  ('pokemon', 'ラフレシア', 'くさ・どく', '全国図鑑No.0045。Pokémon Championsで使用できるポケモン。', '{"dexNo":45,"champions":true,"stats":{"hp":75,"attack":80,"defense":85,"spAttack":110,"spDefense":90,"speed":50}}'),
  ('pokemon', 'ウインディ', 'ほのお', '全国図鑑No.0059。Pokémon Championsで使用できるポケモン。', '{"dexNo":59,"champions":true,"stats":{"hp":90,"attack":110,"defense":80,"spAttack":100,"spDefense":80,"speed":95}}'),
  ('pokemon', 'フーディン', 'エスパー', '全国図鑑No.0065。Pokémon Championsで使用できるポケモン。', '{"dexNo":65,"champions":true,"stats":{"hp":55,"attack":50,"defense":45,"spAttack":135,"spDefense":95,"speed":120}}'),
  ('pokemon', 'カイリキー', 'かくとう', '全国図鑑No.0068。Pokémon Championsで使用できるポケモン。', '{"dexNo":68,"champions":true,"stats":{"hp":90,"attack":130,"defense":80,"spAttack":65,"spDefense":85,"speed":55}}'),
  ('pokemon', 'ウツボット', 'くさ・どく', '全国図鑑No.0071。Pokémon Championsで使用できるポケモン。', '{"dexNo":71,"champions":true,"stats":{"hp":80,"attack":105,"defense":65,"spAttack":100,"spDefense":70,"speed":70}}'),
  ('pokemon', 'ヤドラン', 'みず・エスパー', '全国図鑑No.0080。Pokémon Championsで使用できるポケモン。', '{"dexNo":80,"champions":true,"stats":{"hp":95,"attack":75,"defense":110,"spAttack":100,"spDefense":80,"speed":30}}'),
  ('pokemon', 'ゲンガー', 'ゴースト・どく', '全国図鑑No.0094。Pokémon Championsで使用できるポケモン。', '{"dexNo":94,"champions":true,"stats":{"hp":60,"attack":65,"defense":60,"spAttack":130,"spDefense":75,"speed":110}}'),
  ('pokemon', 'ガルーラ', 'ノーマル', '全国図鑑No.0115。Pokémon Championsで使用できるポケモン。', '{"dexNo":115,"champions":true,"stats":{"hp":105,"attack":95,"defense":80,"spAttack":40,"spDefense":80,"speed":90}}'),
  ('pokemon', 'スターミー', 'みず・エスパー', '全国図鑑No.0121。Pokémon Championsで使用できるポケモン。', '{"dexNo":121,"champions":true,"stats":{"hp":60,"attack":75,"defense":85,"spAttack":100,"spDefense":85,"speed":115}}'),
  ('pokemon', 'カイロス', 'むし', '全国図鑑No.0127。Pokémon Championsで使用できるポケモン。', '{"dexNo":127,"champions":true,"stats":{"hp":65,"attack":125,"defense":100,"spAttack":55,"spDefense":70,"speed":85}}'),
  ('pokemon', 'ケンタロス', 'ノーマル', '全国図鑑No.0128。Pokémon Championsで使用できるポケモン。', '{"dexNo":128,"champions":true,"stats":{"hp":75,"attack":100,"defense":95,"spAttack":40,"spDefense":70,"speed":110}}'),
  ('pokemon', 'ギャラドス', 'みず・ひこう', '全国図鑑No.0130。Pokémon Championsで使用できるポケモン。', '{"dexNo":130,"champions":true,"stats":{"hp":95,"attack":125,"defense":79,"spAttack":60,"spDefense":100,"speed":81}}'),
  ('pokemon', 'メタモン', 'ノーマル', '全国図鑑No.0132。Pokémon Championsで使用できるポケモン。', '{"dexNo":132,"champions":true,"stats":{"hp":48,"attack":48,"defense":48,"spAttack":48,"spDefense":48,"speed":48}}'),
  ('pokemon', 'シャワーズ', 'みず', '全国図鑑No.0134。Pokémon Championsで使用できるポケモン。', '{"dexNo":134,"champions":true,"stats":{"hp":130,"attack":65,"defense":60,"spAttack":110,"spDefense":95,"speed":65}}'),
  ('pokemon', 'サンダース', 'でんき', '全国図鑑No.0135。Pokémon Championsで使用できるポケモン。', '{"dexNo":135,"champions":true,"stats":{"hp":65,"attack":65,"defense":60,"spAttack":110,"spDefense":95,"speed":130}}'),
  ('pokemon', 'ブースター', 'ほのお', '全国図鑑No.0136。Pokémon Championsで使用できるポケモン。', '{"dexNo":136,"champions":true,"stats":{"hp":65,"attack":130,"defense":60,"spAttack":95,"spDefense":110,"speed":65}}'),
  ('pokemon', 'プテラ', 'いわ・ひこう', '全国図鑑No.0142。Pokémon Championsで使用できるポケモン。', '{"dexNo":142,"champions":true,"stats":{"hp":80,"attack":105,"defense":65,"spAttack":60,"spDefense":75,"speed":130}}'),
  ('pokemon', 'カビゴン', 'ノーマル', '全国図鑑No.0143。Pokémon Championsで使用できるポケモン。', '{"dexNo":143,"champions":true,"stats":{"hp":160,"attack":110,"defense":65,"spAttack":65,"spDefense":110,"speed":30}}'),
  ('pokemon', 'カイリュー', 'ドラゴン・ひこう', '全国図鑑No.0149。Pokémon Championsで使用できるポケモン。', '{"dexNo":149,"champions":true,"stats":{"hp":91,"attack":134,"defense":95,"spAttack":100,"spDefense":100,"speed":80}}'),
  ('pokemon', 'メガニウム', 'くさ', '全国図鑑No.0154。Pokémon Championsで使用できるポケモン。', '{"dexNo":154,"champions":true,"stats":{"hp":80,"attack":82,"defense":100,"spAttack":83,"spDefense":100,"speed":80}}'),
  ('pokemon', 'バクフーン', 'ほのお', '全国図鑑No.0157。Pokémon Championsで使用できるポケモン。', '{"dexNo":157,"champions":true,"stats":{"hp":78,"attack":84,"defense":78,"spAttack":109,"spDefense":85,"speed":100}}'),
  ('pokemon', 'オーダイル', 'みず', '全国図鑑No.0160。Pokémon Championsで使用できるポケモン。', '{"dexNo":160,"champions":true,"stats":{"hp":85,"attack":105,"defense":100,"spAttack":79,"spDefense":83,"speed":78}}'),
  ('pokemon', 'アリアドス', 'むし・どく', '全国図鑑No.0168。Pokémon Championsで使用できるポケモン。', '{"dexNo":168,"champions":true,"stats":{"hp":70,"attack":90,"defense":70,"spAttack":60,"spDefense":70,"speed":40}}'),
  ('pokemon', 'デンリュウ', 'でんき', '全国図鑑No.0181。Pokémon Championsで使用できるポケモン。', '{"dexNo":181,"champions":true,"stats":{"hp":90,"attack":75,"defense":85,"spAttack":115,"spDefense":90,"speed":55}}'),
  ('pokemon', 'マリルリ', 'みず・フェアリー', '全国図鑑No.0184。Pokémon Championsで使用できるポケモン。', '{"dexNo":184,"champions":true,"stats":{"hp":100,"attack":50,"defense":80,"spAttack":60,"spDefense":80,"speed":50}}'),
  ('pokemon', 'ニョロトノ', 'みず', '全国図鑑No.0186。Pokémon Championsで使用できるポケモン。', '{"dexNo":186,"champions":true,"stats":{"hp":90,"attack":75,"defense":75,"spAttack":90,"spDefense":100,"speed":70}}'),
  ('pokemon', 'エーフィ', 'エスパー', '全国図鑑No.0196。Pokémon Championsで使用できるポケモン。', '{"dexNo":196,"champions":true,"stats":{"hp":65,"attack":65,"defense":60,"spAttack":130,"spDefense":95,"speed":110}}'),
  ('pokemon', 'ブラッキー', 'あく', '全国図鑑No.0197。Pokémon Championsで使用できるポケモン。', '{"dexNo":197,"champions":true,"stats":{"hp":95,"attack":65,"defense":110,"spAttack":60,"spDefense":130,"speed":65}}'),
  ('pokemon', 'ヤドキング', 'みず・エスパー', '全国図鑑No.0199。Pokémon Championsで使用できるポケモン。', '{"dexNo":199,"champions":true,"stats":{"hp":95,"attack":75,"defense":80,"spAttack":100,"spDefense":110,"speed":30}}'),
  ('pokemon', 'フォレトス', 'むし・はがね', '全国図鑑No.0205。Pokémon Championsで使用できるポケモン。', '{"dexNo":205,"champions":true,"stats":{"hp":75,"attack":90,"defense":140,"spAttack":60,"spDefense":60,"speed":40}}'),
  ('pokemon', 'ハガネール', 'はがね・じめん', '全国図鑑No.0208。Pokémon Championsで使用できるポケモン。', '{"dexNo":208,"champions":true,"stats":{"hp":75,"attack":85,"defense":200,"spAttack":55,"spDefense":65,"speed":30}}'),
  ('pokemon', 'ハリーセン', 'みず・どく', '全国図鑑No.0211。Pokémon Championsで使用できるポケモン。', '{"dexNo":211,"champions":true,"stats":{"hp":65,"attack":95,"defense":85,"spAttack":55,"spDefense":55,"speed":85}}'),
  ('pokemon', 'ハッサム', 'むし・はがね', '全国図鑑No.0212。Pokémon Championsで使用できるポケモン。', '{"dexNo":212,"champions":true,"stats":{"hp":70,"attack":130,"defense":100,"spAttack":55,"spDefense":80,"speed":65}}'),
  ('pokemon', 'ヘラクロス', 'むし・かくとう', '全国図鑑No.0214。Pokémon Championsで使用できるポケモン。', '{"dexNo":214,"champions":true,"stats":{"hp":80,"attack":125,"defense":75,"spAttack":40,"spDefense":95,"speed":85}}'),
  ('pokemon', 'エアームド', 'はがね・ひこう', '全国図鑑No.0227。Pokémon Championsで使用できるポケモン。', '{"dexNo":227,"champions":true,"stats":{"hp":65,"attack":80,"defense":140,"spAttack":40,"spDefense":70,"speed":70}}'),
  ('pokemon', 'ヘルガー', 'あく・ほのお', '全国図鑑No.0229。Pokémon Championsで使用できるポケモン。', '{"dexNo":229,"champions":true,"stats":{"hp":75,"attack":90,"defense":50,"spAttack":110,"spDefense":80,"speed":95}}'),
  ('pokemon', 'バンギラス', 'いわ・あく', '全国図鑑No.0248。Pokémon Championsで使用できるポケモン。', '{"dexNo":248,"champions":true,"stats":{"hp":100,"attack":134,"defense":110,"spAttack":95,"spDefense":100,"speed":61}}'),
  ('pokemon', 'ジュカイン', 'くさ', '全国図鑑No.0254。Pokémon Championsで使用できるポケモン。', '{"dexNo":254,"champions":true,"stats":{"hp":70,"attack":85,"defense":65,"spAttack":105,"spDefense":85,"speed":120}}'),
  ('pokemon', 'バシャーモ', 'ほのお・かくとう', '全国図鑑No.0257。Pokémon Championsで使用できるポケモン。', '{"dexNo":257,"champions":true,"stats":{"hp":80,"attack":120,"defense":70,"spAttack":110,"spDefense":70,"speed":80}}'),
  ('pokemon', 'ラグラージ', 'みず・じめん', '全国図鑑No.0260。Pokémon Championsで使用できるポケモン。', '{"dexNo":260,"champions":true,"stats":{"hp":100,"attack":110,"defense":90,"spAttack":85,"spDefense":90,"speed":60}}'),
  ('pokemon', 'ペリッパー', 'みず・ひこう', '全国図鑑No.0279。Pokémon Championsで使用できるポケモン。', '{"dexNo":279,"champions":true,"stats":{"hp":60,"attack":50,"defense":100,"spAttack":95,"spDefense":70,"speed":65}}'),
  ('pokemon', 'サーナイト', 'エスパー・フェアリー', '全国図鑑No.0282。Pokémon Championsで使用できるポケモン。', '{"dexNo":282,"champions":true,"stats":{"hp":68,"attack":65,"defense":65,"spAttack":125,"spDefense":115,"speed":80}}'),
  ('pokemon', 'ヤミラミ', 'あく・ゴースト', '全国図鑑No.0302。Pokémon Championsで使用できるポケモン。', '{"dexNo":302,"champions":true,"stats":{"hp":50,"attack":75,"defense":75,"spAttack":65,"spDefense":65,"speed":50}}'),
  ('pokemon', 'クチート', 'はがね・フェアリー', '全国図鑑No.0303。Pokémon Championsで使用できるポケモン。', '{"dexNo":303,"champions":true,"stats":{"hp":50,"attack":85,"defense":85,"spAttack":55,"spDefense":55,"speed":50}}'),
  ('pokemon', 'ボスゴドラ', 'はがね・いわ', '全国図鑑No.0306。Pokémon Championsで使用できるポケモン。', '{"dexNo":306,"champions":true,"stats":{"hp":70,"attack":110,"defense":180,"spAttack":60,"spDefense":60,"speed":50}}'),
  ('pokemon', 'チャーレム', 'かくとう・エスパー', '全国図鑑No.0308。Pokémon Championsで使用できるポケモン。', '{"dexNo":308,"champions":true,"stats":{"hp":60,"attack":60,"defense":75,"spAttack":60,"spDefense":75,"speed":80}}'),
  ('pokemon', 'ライボルト', 'でんき', '全国図鑑No.0310。Pokémon Championsで使用できるポケモン。', '{"dexNo":310,"champions":true,"stats":{"hp":70,"attack":75,"defense":60,"spAttack":105,"spDefense":60,"speed":105}}'),
  ('pokemon', 'サメハダー', 'みず・あく', '全国図鑑No.0319。Pokémon Championsで使用できるポケモン。', '{"dexNo":319,"champions":true,"stats":{"hp":70,"attack":120,"defense":40,"spAttack":95,"spDefense":40,"speed":95}}'),
  ('pokemon', 'バクーダ', 'ほのお・じめん', '全国図鑑No.0323。Pokémon Championsで使用できるポケモン。', '{"dexNo":323,"champions":true,"stats":{"hp":70,"attack":100,"defense":70,"spAttack":105,"spDefense":75,"speed":40}}'),
  ('pokemon', 'コータス', 'ほのお', '全国図鑑No.0324。Pokémon Championsで使用できるポケモン。', '{"dexNo":324,"champions":true,"stats":{"hp":70,"attack":85,"defense":140,"spAttack":85,"spDefense":70,"speed":20}}'),
  ('pokemon', 'チルタリス', 'ドラゴン・ひこう', '全国図鑑No.0334。Pokémon Championsで使用できるポケモン。', '{"dexNo":334,"champions":true,"stats":{"hp":75,"attack":70,"defense":90,"spAttack":70,"spDefense":105,"speed":80}}'),
  ('pokemon', 'ミロカロス', 'みず', '全国図鑑No.0350。Pokémon Championsで使用できるポケモン。', '{"dexNo":350,"champions":true,"stats":{"hp":95,"attack":60,"defense":79,"spAttack":100,"spDefense":125,"speed":81}}'),
  ('pokemon', 'ポワルン', 'ノーマル', '全国図鑑No.0351。Pokémon Championsで使用できるポケモン。', '{"dexNo":351,"champions":true,"stats":{"hp":70,"attack":70,"defense":70,"spAttack":70,"spDefense":70,"speed":70}}'),
  ('pokemon', 'ジュペッタ', 'ゴースト', '全国図鑑No.0354。Pokémon Championsで使用できるポケモン。', '{"dexNo":354,"champions":true,"stats":{"hp":64,"attack":115,"defense":65,"spAttack":83,"spDefense":63,"speed":65}}'),
  ('pokemon', 'チリーン', 'エスパー', '全国図鑑No.0358。Pokémon Championsで使用できるポケモン。', '{"dexNo":358,"champions":true,"stats":{"hp":75,"attack":50,"defense":80,"spAttack":95,"spDefense":90,"speed":65}}'),
  ('pokemon', 'アブソル', 'あく', '全国図鑑No.0359。Pokémon Championsで使用できるポケモン。', '{"dexNo":359,"champions":true,"stats":{"hp":65,"attack":130,"defense":60,"spAttack":75,"spDefense":60,"speed":75}}'),
  ('pokemon', 'オニゴーリ', 'こおり', '全国図鑑No.0362。Pokémon Championsで使用できるポケモン。', '{"dexNo":362,"champions":true,"stats":{"hp":80,"attack":80,"defense":80,"spAttack":80,"spDefense":80,"speed":80}}'),
  ('pokemon', 'メタグロス', 'はがね・エスパー', '全国図鑑No.0376。Pokémon Championsで使用できるポケモン。', '{"dexNo":376,"champions":true,"stats":{"hp":80,"attack":135,"defense":130,"spAttack":95,"spDefense":90,"speed":70}}'),
  ('pokemon', 'ドダイトス', 'くさ・じめん', '全国図鑑No.0389。Pokémon Championsで使用できるポケモン。', '{"dexNo":389,"champions":true,"stats":{"hp":95,"attack":109,"defense":105,"spAttack":75,"spDefense":85,"speed":56}}'),
  ('pokemon', 'ゴウカザル', 'ほのお・かくとう', '全国図鑑No.0392。Pokémon Championsで使用できるポケモン。', '{"dexNo":392,"champions":true,"stats":{"hp":76,"attack":104,"defense":71,"spAttack":104,"spDefense":71,"speed":108}}'),
  ('pokemon', 'エンペルト', 'みず・はがね', '全国図鑑No.0395。Pokémon Championsで使用できるポケモン。', '{"dexNo":395,"champions":true,"stats":{"hp":84,"attack":86,"defense":88,"spAttack":111,"spDefense":101,"speed":60}}'),
  ('pokemon', 'ムクホーク', 'ノーマル・ひこう', '全国図鑑No.0398。Pokémon Championsで使用できるポケモン。', '{"dexNo":398,"champions":true,"stats":{"hp":85,"attack":120,"defense":70,"spAttack":50,"spDefense":60,"speed":100}}'),
  ('pokemon', 'レントラー', 'でんき', '全国図鑑No.0405。Pokémon Championsで使用できるポケモン。', '{"dexNo":405,"champions":true,"stats":{"hp":80,"attack":120,"defense":79,"spAttack":95,"spDefense":79,"speed":70}}'),
  ('pokemon', 'ロズレイド', 'くさ・どく', '全国図鑑No.0407。Pokémon Championsで使用できるポケモン。', '{"dexNo":407,"champions":true,"stats":{"hp":60,"attack":70,"defense":65,"spAttack":125,"spDefense":105,"speed":90}}'),
  ('pokemon', 'ラムパルド', 'いわ', '全国図鑑No.0409。Pokémon Championsで使用できるポケモン。', '{"dexNo":409,"champions":true,"stats":{"hp":97,"attack":165,"defense":60,"spAttack":65,"spDefense":50,"speed":58}}'),
  ('pokemon', 'トリデプス', 'いわ・はがね', '全国図鑑No.0411。Pokémon Championsで使用できるポケモン。', '{"dexNo":411,"champions":true,"stats":{"hp":60,"attack":52,"defense":168,"spAttack":47,"spDefense":138,"speed":30}}'),
  ('pokemon', 'ミミロップ', 'ノーマル', '全国図鑑No.0428。Pokémon Championsで使用できるポケモン。', '{"dexNo":428,"champions":true,"stats":{"hp":65,"attack":76,"defense":84,"spAttack":54,"spDefense":96,"speed":105}}'),
  ('pokemon', 'ミカルゲ', 'ゴースト・あく', '全国図鑑No.0442。Pokémon Championsで使用できるポケモン。', '{"dexNo":442,"champions":true,"stats":{"hp":50,"attack":92,"defense":108,"spAttack":92,"spDefense":108,"speed":35}}'),
  ('pokemon', 'ガブリアス', 'ドラゴン・じめん', '全国図鑑No.0445。Pokémon Championsで使用できるポケモン。', '{"dexNo":445,"champions":true,"stats":{"hp":108,"attack":130,"defense":95,"spAttack":80,"spDefense":85,"speed":102}}'),
  ('pokemon', 'ルカリオ', 'かくとう・はがね', '全国図鑑No.0448。Pokémon Championsで使用できるポケモン。', '{"dexNo":448,"champions":true,"stats":{"hp":70,"attack":110,"defense":70,"spAttack":115,"spDefense":70,"speed":90}}'),
  ('pokemon', 'カバルドン', 'じめん', '全国図鑑No.0450。Pokémon Championsで使用できるポケモン。', '{"dexNo":450,"champions":true,"stats":{"hp":108,"attack":112,"defense":118,"spAttack":68,"spDefense":72,"speed":47}}'),
  ('pokemon', 'ドクロッグ', 'どく・かくとう', '全国図鑑No.0454。Pokémon Championsで使用できるポケモン。', '{"dexNo":454,"champions":true,"stats":{"hp":83,"attack":106,"defense":65,"spAttack":86,"spDefense":65,"speed":85}}'),
  ('pokemon', 'ユキノオー', 'くさ・こおり', '全国図鑑No.0460。Pokémon Championsで使用できるポケモン。', '{"dexNo":460,"champions":true,"stats":{"hp":90,"attack":92,"defense":75,"spAttack":92,"spDefense":85,"speed":60}}'),
  ('pokemon', 'マニューラ', 'あく・こおり', '全国図鑑No.0461。Pokémon Championsで使用できるポケモン。', '{"dexNo":461,"champions":true,"stats":{"hp":70,"attack":120,"defense":65,"spAttack":45,"spDefense":85,"speed":125}}'),
  ('pokemon', 'ドサイドン', 'じめん・いわ', '全国図鑑No.0464。Pokémon Championsで使用できるポケモン。', '{"dexNo":464,"champions":true,"stats":{"hp":115,"attack":140,"defense":130,"spAttack":55,"spDefense":55,"speed":40}}'),
  ('pokemon', 'リーフィア', 'くさ', '全国図鑑No.0470。Pokémon Championsで使用できるポケモン。', '{"dexNo":470,"champions":true,"stats":{"hp":65,"attack":110,"defense":130,"spAttack":60,"spDefense":65,"speed":95}}'),
  ('pokemon', 'グレイシア', 'こおり', '全国図鑑No.0471。Pokémon Championsで使用できるポケモン。', '{"dexNo":471,"champions":true,"stats":{"hp":65,"attack":60,"defense":110,"spAttack":130,"spDefense":95,"speed":65}}'),
  ('pokemon', 'グライオン', 'じめん・ひこう', '全国図鑑No.0472。Pokémon Championsで使用できるポケモン。', '{"dexNo":472,"champions":true,"stats":{"hp":75,"attack":95,"defense":125,"spAttack":45,"spDefense":75,"speed":95}}'),
  ('pokemon', 'マンムー', 'こおり・じめん', '全国図鑑No.0473。Pokémon Championsで使用できるポケモン。', '{"dexNo":473,"champions":true,"stats":{"hp":110,"attack":130,"defense":80,"spAttack":70,"spDefense":60,"speed":80}}'),
  ('pokemon', 'エルレイド', 'エスパー・かくとう', '全国図鑑No.0475。Pokémon Championsで使用できるポケモン。', '{"dexNo":475,"champions":true,"stats":{"hp":68,"attack":125,"defense":65,"spAttack":65,"spDefense":115,"speed":80}}'),
  ('pokemon', 'ユキメノコ', 'こおり・ゴースト', '全国図鑑No.0478。Pokémon Championsで使用できるポケモン。', '{"dexNo":478,"champions":true,"stats":{"hp":70,"attack":80,"defense":70,"spAttack":80,"spDefense":70,"speed":110}}'),
  ('pokemon', 'ロトム', 'でんき・ゴースト', '全国図鑑No.0479。Pokémon Championsで使用できるポケモン。', '{"dexNo":479,"champions":true,"stats":{"hp":50,"attack":50,"defense":77,"spAttack":95,"spDefense":77,"speed":91}}'),
  ('pokemon', 'ジャローダ', 'くさ', '全国図鑑No.0497。Pokémon Championsで使用できるポケモン。', '{"dexNo":497,"champions":true,"stats":{"hp":75,"attack":75,"defense":95,"spAttack":75,"spDefense":95,"speed":113}}'),
  ('pokemon', 'エンブオー', 'ほのお・かくとう', '全国図鑑No.0500。Pokémon Championsで使用できるポケモン。', '{"dexNo":500,"champions":true,"stats":{"hp":110,"attack":123,"defense":65,"spAttack":100,"spDefense":65,"speed":65}}'),
  ('pokemon', 'ダイケンキ', 'みず', '全国図鑑No.0503。Pokémon Championsで使用できるポケモン。', '{"dexNo":503,"champions":true,"stats":{"hp":95,"attack":100,"defense":85,"spAttack":108,"spDefense":70,"speed":70}}'),
  ('pokemon', 'ミルホッグ', 'ノーマル', '全国図鑑No.0505。Pokémon Championsで使用できるポケモン。', '{"dexNo":505,"champions":true,"stats":{"hp":60,"attack":85,"defense":69,"spAttack":60,"spDefense":69,"speed":77}}'),
  ('pokemon', 'レパルダス', 'あく', '全国図鑑No.0510。Pokémon Championsで使用できるポケモン。', '{"dexNo":510,"champions":true,"stats":{"hp":64,"attack":88,"defense":50,"spAttack":88,"spDefense":50,"speed":106}}'),
  ('pokemon', 'ヤナッキー', 'くさ', '全国図鑑No.0512。Pokémon Championsで使用できるポケモン。', '{"dexNo":512,"champions":true,"stats":{"hp":75,"attack":98,"defense":63,"spAttack":98,"spDefense":63,"speed":101}}'),
  ('pokemon', 'バオッキー', 'ほのお', '全国図鑑No.0514。Pokémon Championsで使用できるポケモン。', '{"dexNo":514,"champions":true,"stats":{"hp":75,"attack":98,"defense":63,"spAttack":98,"spDefense":63,"speed":101}}'),
  ('pokemon', 'ヒヤッキー', 'みず', '全国図鑑No.0516。Pokémon Championsで使用できるポケモン。', '{"dexNo":516,"champions":true,"stats":{"hp":75,"attack":98,"defense":63,"spAttack":98,"spDefense":63,"speed":101}}'),
  ('pokemon', 'ムシャーナ', 'エスパー', '全国図鑑No.0518。Pokémon Championsで使用できるポケモン。', '{"dexNo":518,"champions":true,"stats":{"hp":116,"attack":55,"defense":85,"spAttack":107,"spDefense":95,"speed":29}}'),
  ('pokemon', 'ドリュウズ', 'じめん・はがね', '全国図鑑No.0530。Pokémon Championsで使用できるポケモン。', '{"dexNo":530,"champions":true,"stats":{"hp":110,"attack":135,"defense":60,"spAttack":50,"spDefense":65,"speed":88}}'),
  ('pokemon', 'タブンネ', 'ノーマル', '全国図鑑No.0531。Pokémon Championsで使用できるポケモン。', '{"dexNo":531,"champions":true,"stats":{"hp":103,"attack":60,"defense":86,"spAttack":60,"spDefense":86,"speed":50}}'),
  ('pokemon', 'ローブシン', 'かくとう', '全国図鑑No.0534。Pokémon Championsで使用できるポケモン。', '{"dexNo":534,"champions":true,"stats":{"hp":105,"attack":140,"defense":95,"spAttack":55,"spDefense":65,"speed":45}}'),
  ('pokemon', 'ペンドラー', 'むし・どく', '全国図鑑No.0545。Pokémon Championsで使用できるポケモン。', '{"dexNo":545,"champions":true,"stats":{"hp":60,"attack":100,"defense":89,"spAttack":55,"spDefense":69,"speed":112}}'),
  ('pokemon', 'エルフーン', 'くさ・フェアリー', '全国図鑑No.0547。Pokémon Championsで使用できるポケモン。', '{"dexNo":547,"champions":true,"stats":{"hp":60,"attack":67,"defense":85,"spAttack":77,"spDefense":75,"speed":116}}'),
  ('pokemon', 'ワルビアル', 'じめん・あく', '全国図鑑No.0553。Pokémon Championsで使用できるポケモン。', '{"dexNo":553,"champions":true,"stats":{"hp":95,"attack":117,"defense":80,"spAttack":65,"spDefense":70,"speed":92}}'),
  ('pokemon', 'ズルズキン', 'あく・かくとう', '全国図鑑No.0560。Pokémon Championsで使用できるポケモン。', '{"dexNo":560,"champions":true,"stats":{"hp":65,"attack":90,"defense":115,"spAttack":45,"spDefense":115,"speed":58}}'),
  ('pokemon', 'デスカーン', 'ゴースト', '全国図鑑No.0563。Pokémon Championsで使用できるポケモン。', '{"dexNo":563,"champions":true,"stats":{"hp":58,"attack":50,"defense":145,"spAttack":95,"spDefense":105,"speed":30}}'),
  ('pokemon', 'ダストダス', 'どく', '全国図鑑No.0569。Pokémon Championsで使用できるポケモン。', '{"dexNo":569,"champions":true,"stats":{"hp":80,"attack":95,"defense":82,"spAttack":60,"spDefense":82,"speed":75}}'),
  ('pokemon', 'ゾロアーク', 'あく', '全国図鑑No.0571。Pokémon Championsで使用できるポケモン。', '{"dexNo":571,"champions":true,"stats":{"hp":60,"attack":105,"defense":60,"spAttack":120,"spDefense":60,"speed":105}}'),
  ('pokemon', 'ランクルス', 'エスパー', '全国図鑑No.0579。Pokémon Championsで使用できるポケモン。', '{"dexNo":579,"champions":true,"stats":{"hp":110,"attack":65,"defense":75,"spAttack":125,"spDefense":85,"speed":30}}'),
  ('pokemon', 'バイバニラ', 'こおり', '全国図鑑No.0584。Pokémon Championsで使用できるポケモン。', '{"dexNo":584,"champions":true,"stats":{"hp":71,"attack":95,"defense":85,"spAttack":110,"spDefense":95,"speed":79}}'),
  ('pokemon', 'エモンガ', 'でんき・ひこう', '全国図鑑No.0587。Pokémon Championsで使用できるポケモン。', '{"dexNo":587,"champions":true,"stats":{"hp":55,"attack":75,"defense":60,"spAttack":75,"spDefense":60,"speed":103}}'),
  ('pokemon', 'シビルドン', 'でんき', '全国図鑑No.0604。Pokémon Championsで使用できるポケモン。', '{"dexNo":604,"champions":true,"stats":{"hp":85,"attack":115,"defense":80,"spAttack":105,"spDefense":80,"speed":50}}'),
  ('pokemon', 'シャンデラ', 'ゴースト・ほのお', '全国図鑑No.0609。Pokémon Championsで使用できるポケモン。', '{"dexNo":609,"champions":true,"stats":{"hp":60,"attack":55,"defense":90,"spAttack":145,"spDefense":90,"speed":80}}'),
  ('pokemon', 'ツンベアー', 'こおり', '全国図鑑No.0614。Pokémon Championsで使用できるポケモン。', '{"dexNo":614,"champions":true,"stats":{"hp":95,"attack":130,"defense":80,"spAttack":70,"spDefense":80,"speed":50}}'),
  ('pokemon', 'マッギョ', 'じめん・でんき', '全国図鑑No.0618。Pokémon Championsで使用できるポケモン。', '{"dexNo":618,"champions":true,"stats":{"hp":109,"attack":66,"defense":84,"spAttack":81,"spDefense":99,"speed":32}}'),
  ('pokemon', 'ゴルーグ', 'じめん・ゴースト', '全国図鑑No.0623。Pokémon Championsで使用できるポケモン。', '{"dexNo":623,"champions":true,"stats":{"hp":89,"attack":124,"defense":80,"spAttack":55,"spDefense":80,"speed":55}}'),
  ('pokemon', 'サザンドラ', 'あく・ドラゴン', '全国図鑑No.0635。Pokémon Championsで使用できるポケモン。', '{"dexNo":635,"champions":true,"stats":{"hp":92,"attack":105,"defense":90,"spAttack":125,"spDefense":90,"speed":98}}'),
  ('pokemon', 'ウルガモス', 'むし・ほのお', '全国図鑑No.0637。Pokémon Championsで使用できるポケモン。', '{"dexNo":637,"champions":true,"stats":{"hp":85,"attack":60,"defense":65,"spAttack":135,"spDefense":105,"speed":100}}'),
  ('pokemon', 'ブリガロン', 'くさ・かくとう', '全国図鑑No.0652。Pokémon Championsで使用できるポケモン。', '{"dexNo":652,"champions":true,"stats":{"hp":88,"attack":107,"defense":122,"spAttack":74,"spDefense":75,"speed":64}}'),
  ('pokemon', 'マフォクシー', 'ほのお・エスパー', '全国図鑑No.0655。Pokémon Championsで使用できるポケモン。', '{"dexNo":655,"champions":true,"stats":{"hp":75,"attack":69,"defense":72,"spAttack":114,"spDefense":100,"speed":104}}'),
  ('pokemon', 'ゲッコウガ', 'みず・あく', '全国図鑑No.0658。Pokémon Championsで使用できるポケモン。', '{"dexNo":658,"champions":true,"stats":{"hp":72,"attack":95,"defense":67,"spAttack":103,"spDefense":71,"speed":122}}'),
  ('pokemon', 'ホルード', 'ノーマル・じめん', '全国図鑑No.0660。Pokémon Championsで使用できるポケモン。', '{"dexNo":660,"champions":true,"stats":{"hp":85,"attack":56,"defense":77,"spAttack":50,"spDefense":77,"speed":78}}'),
  ('pokemon', 'ファイアロー', 'ほのお・ひこう', '全国図鑑No.0663。Pokémon Championsで使用できるポケモン。', '{"dexNo":663,"champions":true,"stats":{"hp":78,"attack":81,"defense":71,"spAttack":74,"spDefense":69,"speed":126}}'),
  ('pokemon', 'ビビヨン', 'むし・ひこう', '全国図鑑No.0666。Pokémon Championsで使用できるポケモン。', '{"dexNo":666,"champions":true,"stats":{"hp":80,"attack":52,"defense":50,"spAttack":90,"spDefense":50,"speed":89}}'),
  ('pokemon', 'カエンジシ', 'ほのお・ノーマル', '全国図鑑No.0668。Pokémon Championsで使用できるポケモン。', '{"dexNo":668,"champions":true,"stats":{"hp":86,"attack":68,"defense":72,"spAttack":109,"spDefense":66,"speed":106}}'),
  ('pokemon', 'フラエッテ', 'フェアリー', '全国図鑑No.0670。Pokémon Championsで使用できるポケモン。', '{"dexNo":670,"champions":true,"stats":{"hp":54,"attack":45,"defense":47,"spAttack":75,"spDefense":98,"speed":52}}'),
  ('pokemon', 'フラージェス', 'フェアリー', '全国図鑑No.0671。Pokémon Championsで使用できるポケモン。', '{"dexNo":671,"champions":true,"stats":{"hp":78,"attack":65,"defense":68,"spAttack":112,"spDefense":154,"speed":75}}'),
  ('pokemon', 'ゴロンダ', 'かくとう・あく', '全国図鑑No.0675。Pokémon Championsで使用できるポケモン。', '{"dexNo":675,"champions":true,"stats":{"hp":95,"attack":124,"defense":78,"spAttack":69,"spDefense":71,"speed":58}}'),
  ('pokemon', 'トリミアン', 'ノーマル', '全国図鑑No.0676。Pokémon Championsで使用できるポケモン。', '{"dexNo":676,"champions":true,"stats":{"hp":75,"attack":80,"defense":60,"spAttack":65,"spDefense":90,"speed":102}}'),
  ('pokemon', 'ニャオニクス（オスのすがた）', 'エスパー', '全国図鑑No.0678。Pokémon Championsで使用できるポケモン。', '{"dexNo":678,"champions":true,"stats":{"hp":74,"attack":48,"defense":76,"spAttack":83,"spDefense":81,"speed":104}}'),
  ('pokemon', 'ギルガルド（シールドフォルム）', 'はがね・ゴースト', '全国図鑑No.0681。Pokémon Championsで使用できるポケモン。', '{"dexNo":681,"champions":true,"stats":{"hp":60,"attack":50,"defense":140,"spAttack":50,"spDefense":140,"speed":60}}'),
  ('pokemon', 'フレフワン', 'フェアリー', '全国図鑑No.0683。Pokémon Championsで使用できるポケモン。', '{"dexNo":683,"champions":true,"stats":{"hp":101,"attack":72,"defense":72,"spAttack":99,"spDefense":89,"speed":29}}'),
  ('pokemon', 'ペロリーム', 'フェアリー', '全国図鑑No.0685。Pokémon Championsで使用できるポケモン。', '{"dexNo":685,"champions":true,"stats":{"hp":82,"attack":80,"defense":86,"spAttack":85,"spDefense":75,"speed":72}}'),
  ('pokemon', 'カラマネロ', 'あく・エスパー', '全国図鑑No.0687。Pokémon Championsで使用できるポケモン。', '{"dexNo":687,"champions":true,"stats":{"hp":86,"attack":92,"defense":88,"spAttack":68,"spDefense":75,"speed":73}}'),
  ('pokemon', 'ガメノデス', 'いわ・みず', '全国図鑑No.0689。Pokémon Championsで使用できるポケモン。', '{"dexNo":689,"champions":true,"stats":{"hp":72,"attack":105,"defense":115,"spAttack":54,"spDefense":86,"speed":68}}'),
  ('pokemon', 'ドラミドロ', 'どく・ドラゴン', '全国図鑑No.0691。Pokémon Championsで使用できるポケモン。', '{"dexNo":691,"champions":true,"stats":{"hp":65,"attack":75,"defense":90,"spAttack":97,"spDefense":123,"speed":44}}'),
  ('pokemon', 'ブロスター', 'みず', '全国図鑑No.0693。Pokémon Championsで使用できるポケモン。', '{"dexNo":693,"champions":true,"stats":{"hp":71,"attack":73,"defense":88,"spAttack":120,"spDefense":89,"speed":59}}'),
  ('pokemon', 'エレザード', 'でんき・ノーマル', '全国図鑑No.0695。Pokémon Championsで使用できるポケモン。', '{"dexNo":695,"champions":true,"stats":{"hp":62,"attack":55,"defense":52,"spAttack":109,"spDefense":94,"speed":109}}'),
  ('pokemon', 'ガチゴラス', 'いわ・ドラゴン', '全国図鑑No.0697。Pokémon Championsで使用できるポケモン。', '{"dexNo":697,"champions":true,"stats":{"hp":82,"attack":121,"defense":119,"spAttack":69,"spDefense":59,"speed":71}}'),
  ('pokemon', 'アマルルガ', 'いわ・こおり', '全国図鑑No.0699。Pokémon Championsで使用できるポケモン。', '{"dexNo":699,"champions":true,"stats":{"hp":123,"attack":77,"defense":72,"spAttack":99,"spDefense":92,"speed":58}}'),
  ('pokemon', 'ニンフィア', 'フェアリー', '全国図鑑No.0700。Pokémon Championsで使用できるポケモン。', '{"dexNo":700,"champions":true,"stats":{"hp":95,"attack":65,"defense":65,"spAttack":110,"spDefense":130,"speed":60}}'),
  ('pokemon', 'ルチャブル', 'かくとう・ひこう', '全国図鑑No.0701。Pokémon Championsで使用できるポケモン。', '{"dexNo":701,"champions":true,"stats":{"hp":78,"attack":92,"defense":75,"spAttack":74,"spDefense":63,"speed":118}}'),
  ('pokemon', 'デデンネ', 'でんき・フェアリー', '全国図鑑No.0702。Pokémon Championsで使用できるポケモン。', '{"dexNo":702,"champions":true,"stats":{"hp":67,"attack":58,"defense":57,"spAttack":81,"spDefense":67,"speed":101}}'),
  ('pokemon', 'ヌメルゴン', 'ドラゴン', '全国図鑑No.0706。Pokémon Championsで使用できるポケモン。', '{"dexNo":706,"champions":true,"stats":{"hp":90,"attack":100,"defense":70,"spAttack":110,"spDefense":150,"speed":80}}'),
  ('pokemon', 'クレッフィ', 'はがね・フェアリー', '全国図鑑No.0707。Pokémon Championsで使用できるポケモン。', '{"dexNo":707,"champions":true,"stats":{"hp":57,"attack":80,"defense":91,"spAttack":80,"spDefense":87,"speed":75}}'),
  ('pokemon', 'オーロット', 'ゴースト・くさ', '全国図鑑No.0709。Pokémon Championsで使用できるポケモン。', '{"dexNo":709,"champions":true,"stats":{"hp":85,"attack":110,"defense":76,"spAttack":65,"spDefense":82,"speed":56}}'),
  ('pokemon', 'パンプジン（ふつうのサイズ）', 'ゴースト・くさ', '全国図鑑No.0711。Pokémon Championsで使用できるポケモン。', '{"dexNo":711,"champions":true,"stats":{"hp":65,"attack":90,"defense":122,"spAttack":58,"spDefense":75,"speed":84}}'),
  ('pokemon', 'クレベース', 'こおり', '全国図鑑No.0713。Pokémon Championsで使用できるポケモン。', '{"dexNo":713,"champions":true,"stats":{"hp":95,"attack":117,"defense":184,"spAttack":44,"spDefense":46,"speed":28}}'),
  ('pokemon', 'オンバーン', 'ひこう・ドラゴン', '全国図鑑No.0715。Pokémon Championsで使用できるポケモン。', '{"dexNo":715,"champions":true,"stats":{"hp":85,"attack":70,"defense":80,"spAttack":97,"spDefense":80,"speed":123}}'),
  ('pokemon', 'ジュナイパー', 'くさ・ゴースト', '全国図鑑No.0724。Pokémon Championsで使用できるポケモン。', '{"dexNo":724,"champions":true,"stats":{"hp":78,"attack":107,"defense":75,"spAttack":100,"spDefense":100,"speed":70}}'),
  ('pokemon', 'ガオガエン', 'ほのお・あく', '全国図鑑No.0727。Pokémon Championsで使用できるポケモン。', '{"dexNo":727,"champions":true,"stats":{"hp":95,"attack":115,"defense":90,"spAttack":80,"spDefense":90,"speed":60}}'),
  ('pokemon', 'アシレーヌ', 'みず・フェアリー', '全国図鑑No.0730。Pokémon Championsで使用できるポケモン。', '{"dexNo":730,"champions":true,"stats":{"hp":80,"attack":74,"defense":74,"spAttack":126,"spDefense":116,"speed":60}}'),
  ('pokemon', 'ドデカバシ', 'ノーマル・ひこう', '全国図鑑No.0733。Pokémon Championsで使用できるポケモン。', '{"dexNo":733,"champions":true,"stats":{"hp":80,"attack":120,"defense":75,"spAttack":75,"spDefense":75,"speed":60}}'),
  ('pokemon', 'ケケンカニ', 'かくとう・こおり', '全国図鑑No.0740。Pokémon Championsで使用できるポケモン。', '{"dexNo":740,"champions":true,"stats":{"hp":97,"attack":132,"defense":77,"spAttack":62,"spDefense":67,"speed":43}}'),
  ('pokemon', 'ルガルガン（まひるのすがた）', 'いわ', '全国図鑑No.0745。Pokémon Championsで使用できるポケモン。', '{"dexNo":745,"champions":true,"stats":{"hp":75,"attack":115,"defense":65,"spAttack":55,"spDefense":65,"speed":112}}'),
  ('pokemon', 'ドヒドイデ', 'どく・みず', '全国図鑑No.0748。Pokémon Championsで使用できるポケモン。', '{"dexNo":748,"champions":true,"stats":{"hp":50,"attack":63,"defense":152,"spAttack":53,"spDefense":142,"speed":35}}'),
  ('pokemon', 'バンバドロ', 'じめん', '全国図鑑No.0750。Pokémon Championsで使用できるポケモン。', '{"dexNo":750,"champions":true,"stats":{"hp":100,"attack":125,"defense":100,"spAttack":55,"spDefense":85,"speed":35}}'),
  ('pokemon', 'オニシズクモ', 'みず・むし', '全国図鑑No.0752。Pokémon Championsで使用できるポケモン。', '{"dexNo":752,"champions":true,"stats":{"hp":68,"attack":70,"defense":92,"spAttack":50,"spDefense":132,"speed":42}}'),
  ('pokemon', 'エンニュート', 'どく・ほのお', '全国図鑑No.0758。Pokémon Championsで使用できるポケモン。', '{"dexNo":758,"champions":true,"stats":{"hp":68,"attack":64,"defense":60,"spAttack":111,"spDefense":60,"speed":117}}'),
  ('pokemon', 'アマージョ', 'くさ', '全国図鑑No.0763。Pokémon Championsで使用できるポケモン。', '{"dexNo":763,"champions":true,"stats":{"hp":72,"attack":120,"defense":98,"spAttack":50,"spDefense":98,"speed":72}}'),
  ('pokemon', 'ヤレユータン', 'ノーマル・エスパー', '全国図鑑No.0765。Pokémon Championsで使用できるポケモン。', '{"dexNo":765,"champions":true,"stats":{"hp":90,"attack":60,"defense":80,"spAttack":90,"spDefense":110,"speed":60}}'),
  ('pokemon', 'ナゲツケサル', 'かくとう', '全国図鑑No.0766。Pokémon Championsで使用できるポケモン。', '{"dexNo":766,"champions":true,"stats":{"hp":100,"attack":120,"defense":90,"spAttack":40,"spDefense":60,"speed":80}}'),
  ('pokemon', 'ミミッキュ', 'ゴースト・フェアリー', '全国図鑑No.0778。Pokémon Championsで使用できるポケモン。', '{"dexNo":778,"champions":true,"stats":{"hp":55,"attack":90,"defense":80,"spAttack":50,"spDefense":105,"speed":96}}'),
  ('pokemon', 'ジジーロン', 'ノーマル・ドラゴン', '全国図鑑No.0780。Pokémon Championsで使用できるポケモン。', '{"dexNo":780,"champions":true,"stats":{"hp":78,"attack":60,"defense":85,"spAttack":135,"spDefense":91,"speed":36}}'),
  ('pokemon', 'ジャラランガ', 'ドラゴン・かくとう', '全国図鑑No.0784。Pokémon Championsで使用できるポケモン。', '{"dexNo":784,"champions":true,"stats":{"hp":75,"attack":110,"defense":125,"spAttack":100,"spDefense":105,"speed":85}}'),
  ('pokemon', 'アーマーガア', 'ひこう・はがね', '全国図鑑No.0823。Pokémon Championsで使用できるポケモン。', '{"dexNo":823,"champions":true,"stats":{"hp":98,"attack":87,"defense":105,"spAttack":53,"spDefense":85,"speed":67}}'),
  ('pokemon', 'アップリュー', 'くさ・ドラゴン', '全国図鑑No.0841。Pokémon Championsで使用できるポケモン。', '{"dexNo":841,"champions":true,"stats":{"hp":70,"attack":110,"defense":80,"spAttack":95,"spDefense":60,"speed":70}}'),
  ('pokemon', 'タルップル', 'くさ・ドラゴン', '全国図鑑No.0842。Pokémon Championsで使用できるポケモン。', '{"dexNo":842,"champions":true,"stats":{"hp":110,"attack":85,"defense":80,"spAttack":100,"spDefense":80,"speed":30}}'),
  ('pokemon', 'サダイジャ', 'じめん', '全国図鑑No.0844。Pokémon Championsで使用できるポケモン。', '{"dexNo":844,"champions":true,"stats":{"hp":72,"attack":107,"defense":125,"spAttack":65,"spDefense":70,"speed":71}}'),
  ('pokemon', 'ポットデス', 'ゴースト', '全国図鑑No.0855。Pokémon Championsで使用できるポケモン。', '{"dexNo":855,"champions":true,"stats":{"hp":60,"attack":65,"defense":65,"spAttack":134,"spDefense":114,"speed":70}}'),
  ('pokemon', 'ブリムオン', 'エスパー・フェアリー', '全国図鑑No.0858。Pokémon Championsで使用できるポケモン。', '{"dexNo":858,"champions":true,"stats":{"hp":57,"attack":90,"defense":95,"spAttack":136,"spDefense":103,"speed":29}}'),
  ('pokemon', 'オーロンゲ', 'あく・フェアリー', '全国図鑑No.0861。Pokémon Championsで使用できるポケモン。', '{"dexNo":861,"champions":true,"stats":{"hp":95,"attack":120,"defense":65,"spAttack":95,"spDefense":75,"speed":60}}'),
  ('pokemon', 'バリコオル', 'こおり・エスパー', '全国図鑑No.0866。Pokémon Championsで使用できるポケモン。', '{"dexNo":866,"champions":true,"stats":{"hp":80,"attack":85,"defense":75,"spAttack":110,"spDefense":100,"speed":70}}'),
  ('pokemon', 'デスバーン', 'じめん・ゴースト', '全国図鑑No.0867。Pokémon Championsで使用できるポケモン。', '{"dexNo":867,"champions":true,"stats":{"hp":58,"attack":95,"defense":145,"spAttack":50,"spDefense":105,"speed":30}}'),
  ('pokemon', 'マホイップ', 'フェアリー', '全国図鑑No.0869。Pokémon Championsで使用できるポケモン。', '{"dexNo":869,"champions":true,"stats":{"hp":65,"attack":60,"defense":75,"spAttack":110,"spDefense":121,"speed":64}}'),
  ('pokemon', 'タイレーツ', 'かくとう', '全国図鑑No.0870。Pokémon Championsで使用できるポケモン。', '{"dexNo":870,"champions":true,"stats":{"hp":65,"attack":100,"defense":100,"spAttack":70,"spDefense":60,"speed":75}}'),
  ('pokemon', 'モルペコ', 'でんき・あく', '全国図鑑No.0877。Pokémon Championsで使用できるポケモン。', '{"dexNo":877,"champions":true,"stats":{"hp":58,"attack":95,"defense":58,"spAttack":70,"spDefense":58,"speed":97}}'),
  ('pokemon', 'ドラパルト', 'ドラゴン・ゴースト', '全国図鑑No.0887。Pokémon Championsで使用できるポケモン。', '{"dexNo":887,"champions":true,"stats":{"hp":88,"attack":120,"defense":75,"spAttack":100,"spDefense":75,"speed":142}}'),
  ('pokemon', 'アヤシシ', 'ノーマル・エスパー', '全国図鑑No.0899。Pokémon Championsで使用できるポケモン。', '{"dexNo":899,"champions":true,"stats":{"hp":103,"attack":105,"defense":72,"spAttack":105,"spDefense":75,"speed":65}}'),
  ('pokemon', 'バサギリ', 'むし・いわ', '全国図鑑No.0900。Pokémon Championsで使用できるポケモン。', '{"dexNo":900,"champions":true,"stats":{"hp":70,"attack":135,"defense":95,"spAttack":45,"spDefense":70,"speed":85}}'),
  ('pokemon', 'イダイトウ（オスのすがた）', 'みず・ゴースト', '全国図鑑No.0902。Pokémon Championsで使用できるポケモン。', '{"dexNo":902,"champions":true,"stats":{"hp":120,"attack":112,"defense":65,"spAttack":80,"spDefense":75,"speed":78}}'),
  ('pokemon', 'オオニューラ', 'かくとう・どく', '全国図鑑No.0903。Pokémon Championsで使用できるポケモン。', '{"dexNo":903,"champions":true,"stats":{"hp":80,"attack":130,"defense":60,"spAttack":40,"spDefense":80,"speed":120}}'),
  ('pokemon', 'ハリーマン', 'あく・どく', '全国図鑑No.0904。Pokémon Championsで使用できるポケモン。', '{"dexNo":904,"champions":true,"stats":{"hp":85,"attack":115,"defense":95,"spAttack":65,"spDefense":65,"speed":85}}'),
  ('pokemon', 'マスカーニャ', 'くさ・あく', '全国図鑑No.0908。Pokémon Championsで使用できるポケモン。', '{"dexNo":908,"champions":true,"stats":{"hp":76,"attack":110,"defense":70,"spAttack":81,"spDefense":70,"speed":123}}'),
  ('pokemon', 'ラウドボーン', 'ほのお・ゴースト', '全国図鑑No.0911。Pokémon Championsで使用できるポケモン。', '{"dexNo":911,"champions":true,"stats":{"hp":104,"attack":75,"defense":100,"spAttack":110,"spDefense":75,"speed":66}}'),
  ('pokemon', 'ウェーニバル', 'みず・かくとう', '全国図鑑No.0914。Pokémon Championsで使用できるポケモン。', '{"dexNo":914,"champions":true,"stats":{"hp":85,"attack":120,"defense":80,"spAttack":85,"spDefense":75,"speed":85}}'),
  ('pokemon', 'イッカネズミ', 'ノーマル', '全国図鑑No.0925。Pokémon Championsで使用できるポケモン。', '{"dexNo":925,"champions":true,"stats":{"hp":74,"attack":75,"defense":70,"spAttack":65,"spDefense":75,"speed":111}}'),
  ('pokemon', 'キョジオーン', 'いわ', '全国図鑑No.0934。Pokémon Championsで使用できるポケモン。', '{"dexNo":934,"champions":true,"stats":{"hp":100,"attack":100,"defense":130,"spAttack":45,"spDefense":90,"speed":35}}'),
  ('pokemon', 'グレンアルマ', 'ほのお・エスパー', '全国図鑑No.0936。Pokémon Championsで使用できるポケモン。', '{"dexNo":936,"champions":true,"stats":{"hp":85,"attack":60,"defense":100,"spAttack":125,"spDefense":80,"speed":75}}'),
  ('pokemon', 'ソウブレイズ', 'ほのお・ゴースト', '全国図鑑No.0937。Pokémon Championsで使用できるポケモン。', '{"dexNo":937,"champions":true,"stats":{"hp":75,"attack":125,"defense":80,"spAttack":60,"spDefense":100,"speed":85}}'),
  ('pokemon', 'ハラバリー', 'でんき', '全国図鑑No.0939。Pokémon Championsで使用できるポケモン。', '{"dexNo":939,"champions":true,"stats":{"hp":109,"attack":64,"defense":91,"spAttack":103,"spDefense":83,"speed":45}}'),
  ('pokemon', 'スコヴィラン', 'くさ・ほのお', '全国図鑑No.0952。Pokémon Championsで使用できるポケモン。', '{"dexNo":952,"champions":true,"stats":{"hp":65,"attack":108,"defense":65,"spAttack":108,"spDefense":65,"speed":75}}'),
  ('pokemon', 'クエスパトラ', 'エスパー', '全国図鑑No.0956。Pokémon Championsで使用できるポケモン。', '{"dexNo":956,"champions":true,"stats":{"hp":95,"attack":60,"defense":60,"spAttack":101,"spDefense":60,"speed":105}}'),
  ('pokemon', 'デカヌチャン', 'フェアリー・はがね', '全国図鑑No.0959。Pokémon Championsで使用できるポケモン。', '{"dexNo":959,"champions":true,"stats":{"hp":85,"attack":75,"defense":77,"spAttack":70,"spDefense":105,"speed":94}}'),
  ('pokemon', 'イルカマン（ナイーブフォルム）', 'みず', '全国図鑑No.0964。Pokémon Championsで使用できるポケモン。', '{"dexNo":964,"champions":true,"stats":{"hp":100,"attack":70,"defense":72,"spAttack":53,"spDefense":62,"speed":100}}'),
  ('pokemon', 'ミミズズ', 'はがね', '全国図鑑No.0968。Pokémon Championsで使用できるポケモン。', '{"dexNo":968,"champions":true,"stats":{"hp":70,"attack":85,"defense":145,"spAttack":60,"spDefense":55,"speed":65}}'),
  ('pokemon', 'キラフロル', 'いわ・どく', '全国図鑑No.0970。Pokémon Championsで使用できるポケモン。', '{"dexNo":970,"champions":true,"stats":{"hp":83,"attack":55,"defense":90,"spAttack":130,"spDefense":81,"speed":86}}'),
  ('pokemon', 'ハカドッグ', 'ゴースト', '全国図鑑No.0972。Pokémon Championsで使用できるポケモン。', '{"dexNo":972,"champions":true,"stats":{"hp":72,"attack":101,"defense":100,"spAttack":50,"spDefense":97,"speed":68}}'),
  ('pokemon', 'コノヨザル', 'かくとう・ゴースト', '全国図鑑No.0979。Pokémon Championsで使用できるポケモン。', '{"dexNo":979,"champions":true,"stats":{"hp":110,"attack":115,"defense":80,"spAttack":50,"spDefense":90,"speed":90}}'),
  ('pokemon', 'リキキリン', 'ノーマル・エスパー', '全国図鑑No.0981。Pokémon Championsで使用できるポケモン。', '{"dexNo":981,"champions":true,"stats":{"hp":120,"attack":90,"defense":70,"spAttack":110,"spDefense":70,"speed":60}}'),
  ('pokemon', 'ドドゲザン', 'あく・はがね', '全国図鑑No.0983。Pokémon Championsで使用できるポケモン。', '{"dexNo":983,"champions":true,"stats":{"hp":100,"attack":135,"defense":120,"spAttack":60,"spDefense":85,"speed":50}}'),
  ('pokemon', 'サーフゴー', 'はがね・ゴースト', '全国図鑑No.1000。Pokémon Championsで使用できるポケモン。', '{"dexNo":1000,"champions":true,"stats":{"hp":87,"attack":60,"defense":95,"spAttack":133,"spDefense":91,"speed":84}}'),
  ('pokemon', 'ヤバソチャ', 'くさ・ゴースト', '全国図鑑No.1013。Pokémon Championsで使用できるポケモン。', '{"dexNo":1013,"champions":true,"stats":{"hp":71,"attack":60,"defense":106,"spAttack":121,"spDefense":80,"speed":70}}'),
  ('pokemon', 'ブリジュラス', 'はがね・ドラゴン', '全国図鑑No.1018。Pokémon Championsで使用できるポケモン。', '{"dexNo":1018,"champions":true,"stats":{"hp":90,"attack":105,"defense":130,"spAttack":125,"spDefense":65,"speed":85}}'),
  ('pokemon', 'カミツオロチ', 'くさ・ドラゴン', '全国図鑑No.1019。Pokémon Championsで使用できるポケモン。', '{"dexNo":1019,"champions":true,"stats":{"hp":106,"attack":80,"defense":110,"spAttack":120,"spDefense":80,"speed":44}}'),
  ('form', 'メガフシギバナ', 'くさ・どく', 'フシギバナのメガシンカ。', '{"dexNo":3,"baseName":"フシギバナ","champions":true,"mega":true,"stats":{"hp":80,"attack":100,"defense":123,"spAttack":122,"spDefense":120,"speed":80}}'),
  ('form', 'メガリザードンX', 'ほのお・ドラゴン', 'リザードンのメガシンカ。', '{"dexNo":6,"baseName":"リザードン","champions":true,"mega":true,"stats":{"hp":78,"attack":130,"defense":111,"spAttack":130,"spDefense":85,"speed":100}}'),
  ('form', 'メガリザードンY', 'ほのお・ひこう', 'リザードンのメガシンカ。', '{"dexNo":6,"baseName":"リザードン","champions":true,"mega":true,"stats":{"hp":78,"attack":104,"defense":78,"spAttack":159,"spDefense":115,"speed":100}}'),
  ('form', 'メガカメックス', 'みず', 'カメックスのメガシンカ。', '{"dexNo":9,"baseName":"カメックス","champions":true,"mega":true,"stats":{"hp":79,"attack":103,"defense":120,"spAttack":135,"spDefense":115,"speed":78}}'),
  ('form', 'メガスピアー', 'むし・どく', 'スピアーのメガシンカ。', '{"dexNo":15,"baseName":"スピアー","champions":true,"mega":true,"stats":{"hp":65,"attack":150,"defense":40,"spAttack":15,"spDefense":80,"speed":145}}'),
  ('form', 'メガピジョット', 'ノーマル・ひこう', 'ピジョットのメガシンカ。', '{"dexNo":18,"baseName":"ピジョット","champions":true,"mega":true,"stats":{"hp":83,"attack":80,"defense":80,"spAttack":135,"spDefense":80,"speed":121}}'),
  ('form', 'メガライチュウX', 'でんき', 'ライチュウのメガシンカ。', '{"dexNo":26,"baseName":"ライチュウ","champions":true,"mega":true,"stats":{"hp":60,"attack":135,"defense":95,"spAttack":90,"spDefense":95,"speed":110}}'),
  ('form', 'メガライチュウY', 'でんき', 'ライチュウのメガシンカ。', '{"dexNo":26,"baseName":"ライチュウ","champions":true,"mega":true,"stats":{"hp":60,"attack":100,"defense":55,"spAttack":160,"spDefense":80,"speed":130}}'),
  ('form', 'メガピクシー', 'フェアリー・ひこう', 'ピクシーのメガシンカ。', '{"dexNo":36,"baseName":"ピクシー","champions":true,"mega":true,"stats":{"hp":95,"attack":80,"defense":93,"spAttack":135,"spDefense":110,"speed":70}}'),
  ('form', 'メガフーディン', 'エスパー', 'フーディンのメガシンカ。', '{"dexNo":65,"baseName":"フーディン","champions":true,"mega":true,"stats":{"hp":55,"attack":50,"defense":65,"spAttack":175,"spDefense":105,"speed":150}}'),
  ('form', 'メガウツボット', 'くさ・どく', 'ウツボットのメガシンカ。', '{"dexNo":71,"baseName":"ウツボット","champions":true,"mega":true,"stats":{"hp":80,"attack":125,"defense":85,"spAttack":135,"spDefense":95,"speed":70}}'),
  ('form', 'メガヤドラン', 'みず・エスパー', 'ヤドランのメガシンカ。', '{"dexNo":80,"baseName":"ヤドラン","champions":true,"mega":true,"stats":{"hp":95,"attack":75,"defense":180,"spAttack":130,"spDefense":80,"speed":30}}'),
  ('form', 'メガゲンガー', 'ゴースト・どく', 'ゲンガーのメガシンカ。', '{"dexNo":94,"baseName":"ゲンガー","champions":true,"mega":true,"stats":{"hp":60,"attack":65,"defense":80,"spAttack":170,"spDefense":95,"speed":130}}'),
  ('form', 'メガガルーラ', 'ノーマル', 'ガルーラのメガシンカ。', '{"dexNo":115,"baseName":"ガルーラ","champions":true,"mega":true,"stats":{"hp":105,"attack":125,"defense":100,"spAttack":60,"spDefense":100,"speed":100}}'),
  ('form', 'メガスターミー', 'みず・エスパー', 'スターミーのメガシンカ。', '{"dexNo":121,"baseName":"スターミー","champions":true,"mega":true,"stats":{"hp":60,"attack":100,"defense":105,"spAttack":130,"spDefense":105,"speed":120}}'),
  ('form', 'メガカイロス', 'むし・ひこう', 'カイロスのメガシンカ。', '{"dexNo":127,"baseName":"カイロス","champions":true,"mega":true,"stats":{"hp":65,"attack":155,"defense":120,"spAttack":65,"spDefense":90,"speed":105}}'),
  ('form', 'メガギャラドス', 'みず・あく', 'ギャラドスのメガシンカ。', '{"dexNo":130,"baseName":"ギャラドス","champions":true,"mega":true,"stats":{"hp":95,"attack":155,"defense":109,"spAttack":70,"spDefense":130,"speed":81}}'),
  ('form', 'メガプテラ', 'いわ・ひこう', 'プテラのメガシンカ。', '{"dexNo":142,"baseName":"プテラ","champions":true,"mega":true,"stats":{"hp":80,"attack":135,"defense":85,"spAttack":70,"spDefense":95,"speed":150}}'),
  ('form', 'メガカイリュー', 'ドラゴン・ひこう', 'カイリューのメガシンカ。', '{"dexNo":149,"baseName":"カイリュー","champions":true,"mega":true,"stats":{"hp":91,"attack":124,"defense":115,"spAttack":145,"spDefense":125,"speed":100}}'),
  ('form', 'メガメガニウム', 'くさ・フェアリー', 'メガニウムのメガシンカ。', '{"dexNo":154,"baseName":"メガニウム","champions":true,"mega":true,"stats":{"hp":80,"attack":92,"defense":115,"spAttack":143,"spDefense":115,"speed":80}}'),
  ('form', 'メガオーダイル', 'みず・ドラゴン', 'オーダイルのメガシンカ。', '{"dexNo":160,"baseName":"オーダイル","champions":true,"mega":true,"stats":{"hp":85,"attack":160,"defense":125,"spAttack":89,"spDefense":93,"speed":78}}'),
  ('form', 'メガデンリュウ', 'でんき・ドラゴン', 'デンリュウのメガシンカ。', '{"dexNo":181,"baseName":"デンリュウ","champions":true,"mega":true,"stats":{"hp":90,"attack":95,"defense":105,"spAttack":165,"spDefense":110,"speed":45}}'),
  ('form', 'メガハガネール', 'はがね・じめん', 'ハガネールのメガシンカ。', '{"dexNo":208,"baseName":"ハガネール","champions":true,"mega":true,"stats":{"hp":75,"attack":125,"defense":230,"spAttack":55,"spDefense":95,"speed":30}}'),
  ('form', 'メガハッサム', 'むし・はがね', 'ハッサムのメガシンカ。', '{"dexNo":212,"baseName":"ハッサム","champions":true,"mega":true,"stats":{"hp":70,"attack":150,"defense":140,"spAttack":65,"spDefense":100,"speed":75}}'),
  ('form', 'メガヘラクロス', 'むし・かくとう', 'ヘラクロスのメガシンカ。', '{"dexNo":214,"baseName":"ヘラクロス","champions":true,"mega":true,"stats":{"hp":80,"attack":185,"defense":115,"spAttack":40,"spDefense":105,"speed":75}}'),
  ('form', 'メガエアームド', 'はがね・ひこう', 'エアームドのメガシンカ。', '{"dexNo":227,"baseName":"エアームド","champions":true,"mega":true,"stats":{"hp":65,"attack":140,"defense":110,"spAttack":40,"spDefense":100,"speed":110}}'),
  ('form', 'メガヘルガー', 'あく・ほのお', 'ヘルガーのメガシンカ。', '{"dexNo":229,"baseName":"ヘルガー","champions":true,"mega":true,"stats":{"hp":75,"attack":90,"defense":90,"spAttack":140,"spDefense":90,"speed":115}}'),
  ('form', 'メガバンギラス', 'いわ・あく', 'バンギラスのメガシンカ。', '{"dexNo":248,"baseName":"バンギラス","champions":true,"mega":true,"stats":{"hp":100,"attack":164,"defense":150,"spAttack":95,"spDefense":120,"speed":71}}'),
  ('form', 'メガジュカイン', 'くさ・ドラゴン', 'ジュカインのメガシンカ。', '{"dexNo":254,"baseName":"ジュカイン","champions":true,"mega":true,"stats":{"hp":70,"attack":110,"defense":75,"spAttack":145,"spDefense":85,"speed":145}}'),
  ('form', 'メガバシャーモ', 'ほのお・かくとう', 'バシャーモのメガシンカ。', '{"dexNo":257,"baseName":"バシャーモ","champions":true,"mega":true,"stats":{"hp":80,"attack":160,"defense":80,"spAttack":130,"spDefense":80,"speed":100}}'),
  ('form', 'メガラグラージ', 'みず・じめん', 'ラグラージのメガシンカ。', '{"dexNo":260,"baseName":"ラグラージ","champions":true,"mega":true,"stats":{"hp":100,"attack":150,"defense":110,"spAttack":95,"spDefense":110,"speed":70}}'),
  ('form', 'メガサーナイト', 'エスパー・フェアリー', 'サーナイトのメガシンカ。', '{"dexNo":282,"baseName":"サーナイト","champions":true,"mega":true,"stats":{"hp":68,"attack":85,"defense":65,"spAttack":165,"spDefense":135,"speed":100}}'),
  ('form', 'メガヤミラミ', 'あく・ゴースト', 'ヤミラミのメガシンカ。', '{"dexNo":302,"baseName":"ヤミラミ","champions":true,"mega":true,"stats":{"hp":50,"attack":85,"defense":125,"spAttack":85,"spDefense":115,"speed":20}}'),
  ('form', 'メガクチート', 'はがね・フェアリー', 'クチートのメガシンカ。', '{"dexNo":303,"baseName":"クチート","champions":true,"mega":true,"stats":{"hp":50,"attack":105,"defense":125,"spAttack":55,"spDefense":95,"speed":50}}'),
  ('form', 'メガボスゴドラ', 'はがね', 'ボスゴドラのメガシンカ。', '{"dexNo":306,"baseName":"ボスゴドラ","champions":true,"mega":true,"stats":{"hp":70,"attack":140,"defense":230,"spAttack":60,"spDefense":80,"speed":50}}'),
  ('form', 'メガチャーレム', 'かくとう・エスパー', 'チャーレムのメガシンカ。', '{"dexNo":308,"baseName":"チャーレム","champions":true,"mega":true,"stats":{"hp":60,"attack":100,"defense":85,"spAttack":80,"spDefense":85,"speed":100}}'),
  ('form', 'メガライボルト', 'でんき', 'ライボルトのメガシンカ。', '{"dexNo":310,"baseName":"ライボルト","champions":true,"mega":true,"stats":{"hp":70,"attack":75,"defense":80,"spAttack":135,"spDefense":80,"speed":135}}'),
  ('form', 'メガサメハダー', 'みず・あく', 'サメハダーのメガシンカ。', '{"dexNo":319,"baseName":"サメハダー","champions":true,"mega":true,"stats":{"hp":70,"attack":140,"defense":70,"spAttack":110,"spDefense":65,"speed":105}}'),
  ('form', 'メガバクーダ', 'ほのお・じめん', 'バクーダのメガシンカ。', '{"dexNo":323,"baseName":"バクーダ","champions":true,"mega":true,"stats":{"hp":70,"attack":120,"defense":100,"spAttack":145,"spDefense":105,"speed":20}}'),
  ('form', 'メガチルタリス', 'ドラゴン・フェアリー', 'チルタリスのメガシンカ。', '{"dexNo":334,"baseName":"チルタリス","champions":true,"mega":true,"stats":{"hp":75,"attack":110,"defense":110,"spAttack":110,"spDefense":105,"speed":80}}'),
  ('form', 'メガジュペッタ', 'ゴースト', 'ジュペッタのメガシンカ。', '{"dexNo":354,"baseName":"ジュペッタ","champions":true,"mega":true,"stats":{"hp":64,"attack":165,"defense":75,"spAttack":93,"spDefense":83,"speed":75}}'),
  ('form', 'メガチリーン', 'エスパー・はがね', 'チリーンのメガシンカ。', '{"dexNo":358,"baseName":"チリーン","champions":true,"mega":true,"stats":{"hp":75,"attack":50,"defense":110,"spAttack":135,"spDefense":120,"speed":65}}'),
  ('form', 'メガアブソル', 'あく', 'アブソルのメガシンカ。', '{"dexNo":359,"baseName":"アブソル","champions":true,"mega":true,"stats":{"hp":65,"attack":150,"defense":60,"spAttack":115,"spDefense":60,"speed":115}}'),
  ('form', 'メガオニゴーリ', 'こおり', 'オニゴーリのメガシンカ。', '{"dexNo":362,"baseName":"オニゴーリ","champions":true,"mega":true,"stats":{"hp":80,"attack":120,"defense":80,"spAttack":120,"spDefense":80,"speed":100}}'),
  ('form', 'メガメタグロス', 'はがね・エスパー', 'メタグロスのメガシンカ。', '{"dexNo":376,"baseName":"メタグロス","champions":true,"mega":true,"stats":{"hp":80,"attack":145,"defense":150,"spAttack":105,"spDefense":110,"speed":110}}'),
  ('form', 'メガムクホーク', 'かくとう・ひこう', 'ムクホークのメガシンカ。', '{"dexNo":398,"baseName":"ムクホーク","champions":true,"mega":true,"stats":{"hp":85,"attack":140,"defense":100,"spAttack":60,"spDefense":90,"speed":110}}'),
  ('form', 'メガミミロップ', 'ノーマル・かくとう', 'ミミロップのメガシンカ。', '{"dexNo":428,"baseName":"ミミロップ","champions":true,"mega":true,"stats":{"hp":65,"attack":136,"defense":94,"spAttack":54,"spDefense":96,"speed":135}}'),
  ('form', 'メガガブリアス', 'ドラゴン・じめん', 'ガブリアスのメガシンカ。', '{"dexNo":445,"baseName":"ガブリアス","champions":true,"mega":true,"stats":{"hp":108,"attack":170,"defense":115,"spAttack":120,"spDefense":95,"speed":92}}'),
  ('form', 'メガルカリオ', 'かくとう・はがね', 'ルカリオのメガシンカ。', '{"dexNo":448,"baseName":"ルカリオ","champions":true,"mega":true,"stats":{"hp":70,"attack":145,"defense":88,"spAttack":140,"spDefense":70,"speed":112}}'),
  ('form', 'メガユキノオー', 'くさ・こおり', 'ユキノオーのメガシンカ。', '{"dexNo":460,"baseName":"ユキノオー","champions":true,"mega":true,"stats":{"hp":90,"attack":132,"defense":105,"spAttack":132,"spDefense":105,"speed":30}}'),
  ('form', 'メガエルレイド', 'エスパー・かくとう', 'エルレイドのメガシンカ。', '{"dexNo":475,"baseName":"エルレイド","champions":true,"mega":true,"stats":{"hp":68,"attack":165,"defense":95,"spAttack":65,"spDefense":115,"speed":110}}'),
  ('form', 'メガユキメノコ', 'こおり・ゴースト', 'ユキメノコのメガシンカ。', '{"dexNo":478,"baseName":"ユキメノコ","champions":true,"mega":true,"stats":{"hp":70,"attack":80,"defense":70,"spAttack":140,"spDefense":100,"speed":120}}'),
  ('form', 'メガエンブオー', 'ほのお・かくとう', 'エンブオーのメガシンカ。', '{"dexNo":500,"baseName":"エンブオー","champions":true,"mega":true,"stats":{"hp":110,"attack":148,"defense":75,"spAttack":110,"spDefense":110,"speed":75}}'),
  ('form', 'メガドリュウズ', 'じめん・はがね', 'ドリュウズのメガシンカ。', '{"dexNo":530,"baseName":"ドリュウズ","champions":true,"mega":true,"stats":{"hp":110,"attack":165,"defense":100,"spAttack":65,"spDefense":65,"speed":103}}'),
  ('form', 'メガタブンネ', 'ノーマル・フェアリー', 'タブンネのメガシンカ。', '{"dexNo":531,"baseName":"タブンネ","champions":true,"mega":true,"stats":{"hp":103,"attack":60,"defense":126,"spAttack":80,"spDefense":126,"speed":50}}'),
  ('form', 'メガペンドラー', 'むし・どく', 'ペンドラーのメガシンカ。', '{"dexNo":545,"baseName":"ペンドラー","champions":true,"mega":true,"stats":{"hp":60,"attack":140,"defense":149,"spAttack":75,"spDefense":99,"speed":62}}'),
  ('form', 'メガズルズキン', 'あく・かくとう', 'ズルズキンのメガシンカ。', '{"dexNo":560,"baseName":"ズルズキン","champions":true,"mega":true,"stats":{"hp":65,"attack":130,"defense":135,"spAttack":55,"spDefense":135,"speed":68}}'),
  ('form', 'メガシビルドン', 'でんき', 'シビルドンのメガシンカ。', '{"dexNo":604,"baseName":"シビルドン","champions":true,"mega":true,"stats":{"hp":85,"attack":145,"defense":80,"spAttack":135,"spDefense":90,"speed":80}}'),
  ('form', 'メガシャンデラ', 'ゴースト・ほのお', 'シャンデラのメガシンカ。', '{"dexNo":609,"baseName":"シャンデラ","champions":true,"mega":true,"stats":{"hp":60,"attack":75,"defense":110,"spAttack":175,"spDefense":110,"speed":90}}'),
  ('form', 'メガゴルーグ', 'じめん・ゴースト', 'ゴルーグのメガシンカ。', '{"dexNo":623,"baseName":"ゴルーグ","champions":true,"mega":true,"stats":{"hp":89,"attack":159,"defense":105,"spAttack":70,"spDefense":105,"speed":55}}'),
  ('form', 'メガブリガロン', 'くさ・かくとう', 'ブリガロンのメガシンカ。', '{"dexNo":652,"baseName":"ブリガロン","champions":true,"mega":true,"stats":{"hp":88,"attack":137,"defense":172,"spAttack":74,"spDefense":115,"speed":44}}'),
  ('form', 'メガマフォクシー', 'ほのお・エスパー', 'マフォクシーのメガシンカ。', '{"dexNo":655,"baseName":"マフォクシー","champions":true,"mega":true,"stats":{"hp":75,"attack":69,"defense":72,"spAttack":159,"spDefense":125,"speed":134}}'),
  ('form', 'メガゲッコウガ', 'みず・あく', 'ゲッコウガのメガシンカ。', '{"dexNo":658,"baseName":"ゲッコウガ","champions":true,"mega":true,"stats":{"hp":72,"attack":125,"defense":77,"spAttack":133,"spDefense":81,"speed":142}}'),
  ('form', 'メガカエンジシ', 'ほのお・ノーマル', 'カエンジシのメガシンカ。', '{"dexNo":668,"baseName":"カエンジシ","champions":true,"mega":true,"stats":{"hp":86,"attack":88,"defense":92,"spAttack":129,"spDefense":86,"speed":126}}'),
  ('form', 'メガフラエッテ', 'フェアリー', 'フラエッテのメガシンカ。', '{"dexNo":670,"baseName":"フラエッテ","champions":true,"mega":true,"stats":{"hp":74,"attack":85,"defense":87,"spAttack":155,"spDefense":148,"speed":102}}'),
  ('form', 'メガニャオニクス（オスのすがた）', 'エスパー', 'ニャオニクス（オスのすがた）のメガシンカ。', '{"dexNo":678,"baseName":"ニャオニクス（オスのすがた）","champions":true,"mega":true,"stats":{"hp":74,"attack":48,"defense":76,"spAttack":143,"spDefense":101,"speed":124}}'),
  ('form', 'メガニャオニクス（メスのすがた）', 'エスパー', 'ニャオニクス（メスのすがた）のメガシンカ。', '{"dexNo":678,"baseName":"ニャオニクス（メスのすがた）","champions":true,"mega":true,"stats":{"hp":74,"attack":48,"defense":76,"spAttack":143,"spDefense":101,"speed":124}}'),
  ('form', 'メガカラマネロ', 'あく・エスパー', 'カラマネロのメガシンカ。', '{"dexNo":687,"baseName":"カラマネロ","champions":true,"mega":true,"stats":{"hp":86,"attack":102,"defense":88,"spAttack":98,"spDefense":120,"speed":88}}'),
  ('form', 'メガガメノデス', 'いわ・かくとう', 'ガメノデスのメガシンカ。', '{"dexNo":689,"baseName":"ガメノデス","champions":true,"mega":true,"stats":{"hp":72,"attack":140,"defense":130,"spAttack":64,"spDefense":106,"speed":88}}'),
  ('form', 'メガドラミドロ', 'どく・ドラゴン', 'ドラミドロのメガシンカ。', '{"dexNo":691,"baseName":"ドラミドロ","champions":true,"mega":true,"stats":{"hp":65,"attack":85,"defense":105,"spAttack":132,"spDefense":163,"speed":44}}'),
  ('form', 'メガルチャブル', 'かくとう・ひこう', 'ルチャブルのメガシンカ。', '{"dexNo":701,"baseName":"ルチャブル","champions":true,"mega":true,"stats":{"hp":78,"attack":137,"defense":100,"spAttack":74,"spDefense":93,"speed":118}}'),
  ('form', 'メガケケンカニ', 'かくとう・こおり', 'ケケンカニのメガシンカ。', '{"dexNo":740,"baseName":"ケケンカニ","champions":true,"mega":true,"stats":{"hp":97,"attack":157,"defense":122,"spAttack":62,"spDefense":107,"speed":33}}'),
  ('form', 'メガジジーロン', 'ノーマル・ドラゴン', 'ジジーロンのメガシンカ。', '{"dexNo":780,"baseName":"ジジーロン","champions":true,"mega":true,"stats":{"hp":78,"attack":85,"defense":110,"spAttack":160,"spDefense":116,"speed":36}}'),
  ('form', 'メガタイレーツ', 'かくとう', 'タイレーツのメガシンカ。', '{"dexNo":870,"baseName":"タイレーツ","champions":true,"mega":true,"stats":{"hp":65,"attack":135,"defense":135,"spAttack":70,"spDefense":65,"speed":100}}'),
  ('form', 'メガスコヴィラン', 'くさ・ほのお', 'スコヴィランのメガシンカ。', '{"dexNo":952,"baseName":"スコヴィラン","champions":true,"mega":true,"stats":{"hp":65,"attack":138,"defense":85,"spAttack":138,"spDefense":85,"speed":75}}'),
  ('form', 'メガキラフロル', 'いわ・どく', 'キラフロルのメガシンカ。', '{"dexNo":970,"baseName":"キラフロル","champions":true,"mega":true,"stats":{"hp":83,"attack":90,"defense":105,"spAttack":150,"spDefense":96,"speed":101}}'),
  ('form', 'ライチュウ（アローラのすがた）', 'でんき・エスパー', 'ライチュウの別フォルム。', '{"dexNo":26,"baseName":"ライチュウ","champions":true,"mega":false,"stats":{"hp":60,"attack":85,"defense":50,"spAttack":95,"spDefense":85,"speed":110}}'),
  ('form', 'キュウコン（アローラのすがた）', 'こおり・フェアリー', 'キュウコンの別フォルム。', '{"dexNo":38,"baseName":"キュウコン","champions":true,"mega":false,"stats":{"hp":73,"attack":67,"defense":75,"spAttack":81,"spDefense":100,"speed":109}}'),
  ('form', 'ウインディ（ヒスイのすがた）', 'ほのお・いわ', 'ウインディの別フォルム。', '{"dexNo":59,"baseName":"ウインディ","champions":true,"mega":false,"stats":{"hp":95,"attack":115,"defense":80,"spAttack":95,"spDefense":80,"speed":90}}'),
  ('form', 'ヤドラン（ガラルのすがた）', 'どく・エスパー', 'ヤドランの別フォルム。', '{"dexNo":80,"baseName":"ヤドラン","champions":true,"mega":false,"stats":{"hp":95,"attack":100,"defense":95,"spAttack":100,"spDefense":70,"speed":30}}'),
  ('form', 'ケンタロス（パルデアのすがた（コンバット種））', 'かくとう', 'ケンタロスの別フォルム。', '{"dexNo":128,"baseName":"ケンタロス","champions":true,"mega":false,"stats":{"hp":75,"attack":110,"defense":105,"spAttack":30,"spDefense":70,"speed":100}}'),
  ('form', 'ケンタロス（パルデアのすがた（ブレイズ種））', 'かくとう・ほのお', 'ケンタロスの別フォルム。', '{"dexNo":128,"baseName":"ケンタロス","champions":true,"mega":false,"stats":{"hp":75,"attack":110,"defense":105,"spAttack":30,"spDefense":70,"speed":100}}'),
  ('form', 'ケンタロス（パルデアのすがた（ウォーター種））', 'かくとう・みず', 'ケンタロスの別フォルム。', '{"dexNo":128,"baseName":"ケンタロス","champions":true,"mega":false,"stats":{"hp":75,"attack":110,"defense":105,"spAttack":30,"spDefense":70,"speed":100}}'),
  ('form', 'バクフーン（ヒスイのすがた）', 'ほのお・ゴースト', 'バクフーンの別フォルム。', '{"dexNo":157,"baseName":"バクフーン","champions":true,"mega":false,"stats":{"hp":73,"attack":84,"defense":78,"spAttack":119,"spDefense":85,"speed":95}}'),
  ('form', 'ヤドキング（ガラルのすがた）', 'どく・エスパー', 'ヤドキングの別フォルム。', '{"dexNo":199,"baseName":"ヤドキング","champions":true,"mega":false,"stats":{"hp":95,"attack":65,"defense":80,"spAttack":110,"spDefense":110,"speed":30}}'),
  ('form', 'ハリーセン（ヒスイのすがた）', 'あく・どく', 'ハリーセンの別フォルム。', '{"dexNo":211,"baseName":"ハリーセン","champions":true,"mega":false,"stats":{"hp":65,"attack":95,"defense":85,"spAttack":55,"spDefense":55,"speed":85}}'),
  ('form', 'ポワルン（たいようのすがた）', 'ほのお', 'ポワルンの別フォルム。', '{"dexNo":351,"baseName":"ポワルン","champions":true,"mega":false,"stats":{"hp":70,"attack":70,"defense":70,"spAttack":70,"spDefense":70,"speed":70}}'),
  ('form', 'ポワルン（あまみずのすがた）', 'みず', 'ポワルンの別フォルム。', '{"dexNo":351,"baseName":"ポワルン","champions":true,"mega":false,"stats":{"hp":70,"attack":70,"defense":70,"spAttack":70,"spDefense":70,"speed":70}}'),
  ('form', 'ポワルン（ゆきぐものすがた）', 'こおり', 'ポワルンの別フォルム。', '{"dexNo":351,"baseName":"ポワルン","champions":true,"mega":false,"stats":{"hp":70,"attack":70,"defense":70,"spAttack":70,"spDefense":70,"speed":70}}'),
  ('form', 'ヒートロトム', 'でんき・ほのお', 'ロトムの別フォルム。', '{"dexNo":479,"baseName":"ロトム","champions":true,"mega":false,"stats":{"hp":50,"attack":65,"defense":107,"spAttack":105,"spDefense":107,"speed":86}}'),
  ('form', 'ウォッシュロトム', 'でんき・みず', 'ロトムの別フォルム。', '{"dexNo":479,"baseName":"ロトム","champions":true,"mega":false,"stats":{"hp":50,"attack":65,"defense":107,"spAttack":105,"spDefense":107,"speed":86}}'),
  ('form', 'フロストロトム', 'でんき・こおり', 'ロトムの別フォルム。', '{"dexNo":479,"baseName":"ロトム","champions":true,"mega":false,"stats":{"hp":50,"attack":65,"defense":107,"spAttack":105,"spDefense":107,"speed":86}}'),
  ('form', 'スピンロトム', 'でんき・ひこう', 'ロトムの別フォルム。', '{"dexNo":479,"baseName":"ロトム","champions":true,"mega":false,"stats":{"hp":50,"attack":65,"defense":107,"spAttack":105,"spDefense":107,"speed":86}}'),
  ('form', 'カットロトム', 'でんき・くさ', 'ロトムの別フォルム。', '{"dexNo":479,"baseName":"ロトム","champions":true,"mega":false,"stats":{"hp":50,"attack":65,"defense":107,"spAttack":105,"spDefense":107,"speed":86}}'),
  ('form', 'ダイケンキ（ヒスイのすがた）', 'みず・あく', 'ダイケンキの別フォルム。', '{"dexNo":503,"baseName":"ダイケンキ","champions":true,"mega":false,"stats":{"hp":90,"attack":108,"defense":80,"spAttack":100,"spDefense":65,"speed":85}}'),
  ('form', 'ゾロアーク（ヒスイのすがた）', 'ノーマル・ゴースト', 'ゾロアークの別フォルム。', '{"dexNo":571,"baseName":"ゾロアーク","champions":true,"mega":false,"stats":{"hp":55,"attack":100,"defense":60,"spAttack":125,"spDefense":60,"speed":110}}'),
  ('form', 'マッギョ（ガラルのすがた）', 'じめん・はがね', 'マッギョの別フォルム。', '{"dexNo":618,"baseName":"マッギョ","champions":true,"mega":false,"stats":{"hp":109,"attack":81,"defense":99,"spAttack":66,"spDefense":84,"speed":32}}'),
  ('form', 'フラエッテ（えいえんのはな）', 'フェアリー', 'フラエッテの別フォルム。', '{"dexNo":670,"baseName":"フラエッテ","champions":true,"mega":false,"stats":{"hp":74,"attack":65,"defense":67,"spAttack":125,"spDefense":128,"speed":92}}'),
  ('form', 'ニャオニクス（メスのすがた）', 'エスパー', 'ニャオニクス（オスのすがた）の別フォルム。', '{"dexNo":678,"baseName":"ニャオニクス（オスのすがた）","champions":true,"mega":false,"stats":{"hp":74,"attack":48,"defense":76,"spAttack":83,"spDefense":81,"speed":104}}'),
  ('form', 'ギルガルド（ブレードフォルム）', 'はがね・ゴースト', 'ギルガルド（シールドフォルム）の別フォルム。', '{"dexNo":681,"baseName":"ギルガルド（シールドフォルム）","champions":true,"mega":false,"stats":{"hp":60,"attack":140,"defense":50,"spAttack":140,"spDefense":50,"speed":60}}'),
  ('form', 'ヌメルゴン（ヒスイのすがた）', 'はがね・ドラゴン', 'ヌメルゴンの別フォルム。', '{"dexNo":706,"baseName":"ヌメルゴン","champions":true,"mega":false,"stats":{"hp":80,"attack":100,"defense":100,"spAttack":110,"spDefense":150,"speed":60}}'),
  ('form', 'パンプジン（ちいさいサイズ）', 'ゴースト・くさ', 'パンプジン（ふつうのサイズ）の別フォルム。', '{"dexNo":711,"baseName":"パンプジン（ふつうのサイズ）","champions":true,"mega":false,"stats":{"hp":55,"attack":85,"defense":122,"spAttack":58,"spDefense":75,"speed":99}}'),
  ('form', 'パンプジン（おおきいサイズ）', 'ゴースト・くさ', 'パンプジン（ふつうのサイズ）の別フォルム。', '{"dexNo":711,"baseName":"パンプジン（ふつうのサイズ）","champions":true,"mega":false,"stats":{"hp":75,"attack":95,"defense":122,"spAttack":58,"spDefense":75,"speed":69}}'),
  ('form', 'パンプジン（とくだいサイズ）', 'ゴースト・くさ', 'パンプジン（ふつうのサイズ）の別フォルム。', '{"dexNo":711,"baseName":"パンプジン（ふつうのサイズ）","champions":true,"mega":false,"stats":{"hp":85,"attack":100,"defense":122,"spAttack":58,"spDefense":75,"speed":54}}'),
  ('form', 'クレベース（ヒスイのすがた）', 'こおり・いわ', 'クレベースの別フォルム。', '{"dexNo":713,"baseName":"クレベース","champions":true,"mega":false,"stats":{"hp":95,"attack":127,"defense":184,"spAttack":34,"spDefense":36,"speed":38}}'),
  ('form', 'ジュナイパー（ヒスイのすがた）', 'くさ・かくとう', 'ジュナイパーの別フォルム。', '{"dexNo":724,"baseName":"ジュナイパー","champions":true,"mega":false,"stats":{"hp":88,"attack":112,"defense":80,"spAttack":95,"spDefense":95,"speed":60}}'),
  ('form', 'ルガルガン（まよなかのすがた）', 'いわ', 'ルガルガン（まひるのすがた）の別フォルム。', '{"dexNo":745,"baseName":"ルガルガン（まひるのすがた）","champions":true,"mega":false,"stats":{"hp":85,"attack":115,"defense":75,"spAttack":55,"spDefense":75,"speed":82}}'),
  ('form', 'ルガルガン（たそがれのすがた）', 'いわ', 'ルガルガン（まひるのすがた）の別フォルム。', '{"dexNo":745,"baseName":"ルガルガン（まひるのすがた）","champions":true,"mega":false,"stats":{"hp":75,"attack":117,"defense":65,"spAttack":55,"spDefense":65,"speed":110}}'),
  ('form', 'イダイトウ（メスのすがた）', 'みず・ゴースト', 'イダイトウ（オスのすがた）の別フォルム。', '{"dexNo":902,"baseName":"イダイトウ（オスのすがた）","champions":true,"mega":false,"stats":{"hp":120,"attack":92,"defense":65,"spAttack":100,"spDefense":75,"speed":78}}'),
  ('form', 'イルカマン（マイティフォルム）', 'みず', 'イルカマン（ナイーブフォルム）の別フォルム。', '{"dexNo":964,"baseName":"イルカマン（ナイーブフォルム）","champions":true,"mega":false,"stats":{"hp":100,"attack":160,"defense":97,"spAttack":106,"spDefense":87,"speed":100}}')
ON CONFLICT (`category`, `name`) DO UPDATE SET
  `type` = excluded.`type`,
  `description` = excluded.`description`,
  `data` = excluded.`data`,
  `updated_at` = CURRENT_TIMESTAMP;
--> statement-breakpoint

WITH `form_seed` (`form_name`, `base_name`) AS (VALUES
  ('メガフシギバナ', 'フシギバナ'),
  ('メガリザードンX', 'リザードン'),
  ('メガリザードンY', 'リザードン'),
  ('メガカメックス', 'カメックス'),
  ('メガスピアー', 'スピアー'),
  ('メガピジョット', 'ピジョット'),
  ('メガライチュウX', 'ライチュウ'),
  ('メガライチュウY', 'ライチュウ'),
  ('メガピクシー', 'ピクシー'),
  ('メガフーディン', 'フーディン'),
  ('メガウツボット', 'ウツボット'),
  ('メガヤドラン', 'ヤドラン'),
  ('メガゲンガー', 'ゲンガー'),
  ('メガガルーラ', 'ガルーラ'),
  ('メガスターミー', 'スターミー'),
  ('メガカイロス', 'カイロス'),
  ('メガギャラドス', 'ギャラドス'),
  ('メガプテラ', 'プテラ'),
  ('メガカイリュー', 'カイリュー'),
  ('メガメガニウム', 'メガニウム'),
  ('メガオーダイル', 'オーダイル'),
  ('メガデンリュウ', 'デンリュウ'),
  ('メガハガネール', 'ハガネール'),
  ('メガハッサム', 'ハッサム'),
  ('メガヘラクロス', 'ヘラクロス'),
  ('メガエアームド', 'エアームド'),
  ('メガヘルガー', 'ヘルガー'),
  ('メガバンギラス', 'バンギラス'),
  ('メガジュカイン', 'ジュカイン'),
  ('メガバシャーモ', 'バシャーモ'),
  ('メガラグラージ', 'ラグラージ'),
  ('メガサーナイト', 'サーナイト'),
  ('メガヤミラミ', 'ヤミラミ'),
  ('メガクチート', 'クチート'),
  ('メガボスゴドラ', 'ボスゴドラ'),
  ('メガチャーレム', 'チャーレム'),
  ('メガライボルト', 'ライボルト'),
  ('メガサメハダー', 'サメハダー'),
  ('メガバクーダ', 'バクーダ'),
  ('メガチルタリス', 'チルタリス'),
  ('メガジュペッタ', 'ジュペッタ'),
  ('メガチリーン', 'チリーン'),
  ('メガアブソル', 'アブソル'),
  ('メガオニゴーリ', 'オニゴーリ'),
  ('メガメタグロス', 'メタグロス'),
  ('メガムクホーク', 'ムクホーク'),
  ('メガミミロップ', 'ミミロップ'),
  ('メガガブリアス', 'ガブリアス'),
  ('メガルカリオ', 'ルカリオ'),
  ('メガユキノオー', 'ユキノオー'),
  ('メガエルレイド', 'エルレイド'),
  ('メガユキメノコ', 'ユキメノコ'),
  ('メガエンブオー', 'エンブオー'),
  ('メガドリュウズ', 'ドリュウズ'),
  ('メガタブンネ', 'タブンネ'),
  ('メガペンドラー', 'ペンドラー'),
  ('メガズルズキン', 'ズルズキン'),
  ('メガシビルドン', 'シビルドン'),
  ('メガシャンデラ', 'シャンデラ'),
  ('メガゴルーグ', 'ゴルーグ'),
  ('メガブリガロン', 'ブリガロン'),
  ('メガマフォクシー', 'マフォクシー'),
  ('メガゲッコウガ', 'ゲッコウガ'),
  ('メガカエンジシ', 'カエンジシ'),
  ('メガフラエッテ', 'フラエッテ'),
  ('メガニャオニクス（オスのすがた）', 'ニャオニクス（オスのすがた）'),
  ('メガニャオニクス（メスのすがた）', 'ニャオニクス（メスのすがた）'),
  ('メガカラマネロ', 'カラマネロ'),
  ('メガガメノデス', 'ガメノデス'),
  ('メガドラミドロ', 'ドラミドロ'),
  ('メガルチャブル', 'ルチャブル'),
  ('メガケケンカニ', 'ケケンカニ'),
  ('メガジジーロン', 'ジジーロン'),
  ('メガタイレーツ', 'タイレーツ'),
  ('メガスコヴィラン', 'スコヴィラン'),
  ('メガキラフロル', 'キラフロル'),
  ('ライチュウ（アローラのすがた）', 'ライチュウ'),
  ('キュウコン（アローラのすがた）', 'キュウコン'),
  ('ウインディ（ヒスイのすがた）', 'ウインディ'),
  ('ヤドラン（ガラルのすがた）', 'ヤドラン'),
  ('ケンタロス（パルデアのすがた（コンバット種））', 'ケンタロス'),
  ('ケンタロス（パルデアのすがた（ブレイズ種））', 'ケンタロス'),
  ('ケンタロス（パルデアのすがた（ウォーター種））', 'ケンタロス'),
  ('バクフーン（ヒスイのすがた）', 'バクフーン'),
  ('ヤドキング（ガラルのすがた）', 'ヤドキング'),
  ('ハリーセン（ヒスイのすがた）', 'ハリーセン'),
  ('ポワルン（たいようのすがた）', 'ポワルン'),
  ('ポワルン（あまみずのすがた）', 'ポワルン'),
  ('ポワルン（ゆきぐものすがた）', 'ポワルン'),
  ('ヒートロトム', 'ロトム'),
  ('ウォッシュロトム', 'ロトム'),
  ('フロストロトム', 'ロトム'),
  ('スピンロトム', 'ロトム'),
  ('カットロトム', 'ロトム'),
  ('ダイケンキ（ヒスイのすがた）', 'ダイケンキ'),
  ('ゾロアーク（ヒスイのすがた）', 'ゾロアーク'),
  ('マッギョ（ガラルのすがた）', 'マッギョ'),
  ('フラエッテ（えいえんのはな）', 'フラエッテ'),
  ('ニャオニクス（メスのすがた）', 'ニャオニクス（オスのすがた）'),
  ('ギルガルド（ブレードフォルム）', 'ギルガルド（シールドフォルム）'),
  ('ヌメルゴン（ヒスイのすがた）', 'ヌメルゴン'),
  ('パンプジン（ちいさいサイズ）', 'パンプジン（ふつうのサイズ）'),
  ('パンプジン（おおきいサイズ）', 'パンプジン（ふつうのサイズ）'),
  ('パンプジン（とくだいサイズ）', 'パンプジン（ふつうのサイズ）'),
  ('クレベース（ヒスイのすがた）', 'クレベース'),
  ('ジュナイパー（ヒスイのすがた）', 'ジュナイパー'),
  ('ルガルガン（まよなかのすがた）', 'ルガルガン（まひるのすがた）'),
  ('ルガルガン（たそがれのすがた）', 'ルガルガン（まひるのすがた）'),
  ('イダイトウ（メスのすがた）', 'イダイトウ（オスのすがた）'),
  ('イルカマン（マイティフォルム）', 'イルカマン（ナイーブフォルム）')
)
INSERT INTO `master_relations` (`source_id`, `target_id`, `kind`, `data`)
SELECT `form`.`id`, `base`.`id`, 'form_of', '{}'
FROM `form_seed`
INNER JOIN `master_data` AS `form` ON `form`.`category` = 'form' AND `form`.`name` = `form_seed`.`form_name`
INNER JOIN `master_data` AS `base` ON `base`.`category` IN ('pokemon', 'form') AND `base`.`name` = `form_seed`.`base_name`
WHERE 1 = 1
ON CONFLICT (`source_id`, `target_id`, `kind`) DO NOTHING;
--> statement-breakpoint

INSERT INTO `master_relations` (`source_id`, `target_id`, `kind`, `data`)
SELECT `regulation`.`id`, `form`.`id`, 'allows_form', '{}'
FROM `master_data` AS `regulation`
CROSS JOIN `master_data` AS `form`
WHERE `regulation`.`category` = 'regulation'
  AND `regulation`.`name` = 'Regulation M-B'
  AND `form`.`category` = 'form'
ON CONFLICT (`source_id`, `target_id`, `kind`) DO NOTHING;
